#!/usr/bin/env python3
"""Translate en.json to es.json, preserving ICU plurals and variable placeholders."""

import json
import re
import shutil
from pathlib import Path

# Load English source
src = Path("/home/diegol/Documentos/wacrm/messages/en.json")
en = json.loads(src.read_text(encoding="utf-8"))

# Comprehensive Spanish translations dictionary
# Key = english text (exact), Value = spanish translation
# This covers EVERY string in en.json

translations = {
    # LoginPage
    "Sign in to accept": "Inicia sesión para aceptar",
    "Welcome back": "Bienvenido de nuevo",
    "Sign in and we'll take you to the invitation.": "Inicia sesión y te llevaremos a la invitación.",
    "Sign in to your account": "Inicia sesión en tu cuenta",
    "Email": "Correo electrónico",
    "you@example.com": "tu@ejemplo.com",
    "Password": "Contraseña",
    "Forgot password?": "¿Olvidaste tu contraseña?",
    "Enter your password": "Ingresa tu contraseña",
    "Signing in...": "Iniciando sesión...",
    "Sign in": "Iniciar sesión",
    "Don't have an account?": "¿No tienes una cuenta?",
    "Create account": "Crear cuenta",

    # Sidebar
    "CRM Template for WhatsApp": "Plantilla CRM para WhatsApp",
    "Dashboard": "Panel",
    "Inbox": "Bandeja",
    "Notifications": "Notificaciones",
    "Contacts": "Contactos",
    "Pipelines": "Tuberías",
    "Broadcasts": "Transmisiones",
    "Automations": "Automatizaciones",
    "Flows": "Flujos",
    "AI Agents": "Agentes de IA",
    "Settings": "Configuración",
    "Beta": "Beta",
    "{count} unread {count, plural, =1 {conversation} other {conversations}}": "{count} no leída {count, plural, =1 {conversación} other {conversaciones}}",
    "{count} unread {count, plural, =1 {notification} other {notifications}}": "{count} no leída {count, plural, =1 {notificación} other {notificaciones}}",
    "Owner": "Propietario",
    "Admin": "Admin",
    "Agent": "Agente",
    "Viewer": "Espectador",
    "Close menu": "Cerrar menú",
    "User": "Usuario",
    "Avatar": "Avatar",
    "Profile": "Perfil",
    "Sign out": "Cerrar sesión",

    # Header (duplicates from Sidebar)
    "Open menu": "Abrir menú",
    "Open account menu": "Abrir menú de cuenta",

    # ModeToggle
    "Switch to {mode} mode": "Cambiar a modo {mode}",

    # Dashboard
    "Live analytics across conversations, contacts, deals, broadcasts, and automations.": "Estadísticas en vivo de conversaciones, contactos, negocios, transmisiones y automatizaciones.",
    "Active Conversations": "Conversaciones activas",
    "New Contacts Today": "Contactos nuevos hoy",
    "Open Deals Value": "Valor de negocios abiertos",
    "Messages Sent Today": "Mensajes enviados hoy",
    "new today vs yesterday": "nuevos hoy vs ayer",
    "vs yesterday": "vs ayer",
    "{count} open {count, plural, =1 {deal} other {deals}}": "{count} {count, plural, =1 {negocio abierto} other {negocios abiertos}}",
    "No change {suffix}": "Sin cambios {suffix}",
    "New Contact": "Nuevo contacto",
    "New Deal": "Nuevo negocio",
    "New Broadcast": "Nueva transmisión",
    "New Automation": "Nueva automatización",
    "Recent Activity": "Actividad reciente",
    "View all →": "Ver todo →",
    "No activity yet": "Aún sin actividad",
    "Activity from messages, deals, broadcasts, and automations will appear here.": "La actividad de mensajes, negocios, transmisiones y automatizaciones aparecerá aquí.",
    "Showing {visible} of {totalLoaded}{plus}": "Mostrando {visible} de {totalLoaded}{plus}",
    "Show": "Mostrar",
    "{sec}s ago": "hace {sec}s",
    "{min}m ago": "hace {min}m",
    "{hr}h ago": "hace {hr}h",
    "{day}d ago": "hace {day}d",
    "Conversations Over Time": "Conversaciones en el tiempo",
    "Daily message volume by direction": "Volumen diario de mensajes por dirección",
    "{count} days": "{count} días",
    "No message activity in this range": "Sin actividad de mensajes en este rango",
    "Send or receive messages to start populating this chart.": "Envía o recibe mensajes para empezar a poblar este gráfico.",
    "Incoming": "Entrantes",
    "Outgoing": "Salientes",
    "{count} incoming": "{count} entrantes",
    "{count} outgoing": "{count} salientes",
    "Conversations per day": "Conversaciones por día",
    "Pipeline Value": "Valor de tubería",
    "Open deals by stage": "Negocios abiertos por etapa",
    "No open deals yet": "Aún sin negocios abiertos",
    "Create deals in Pipelines to see stage breakdowns here.": "Crea negocios en Tuberías para ver el desglose por etapas aquí.",
    "{count} {count, plural, =1 {deal} other {deals}}": "{count} {count, plural, =1 {negocio} other {negocios}}",
    "Total": "Total",
    "Pipeline value by stage": "Valor de tubería por etapa",
    "Average First Response Time": "Tiempo promedio de primera respuesta",
    "Minutes to reply to a customer's first unreplied message, by weekday": "Minutos para responder al primer mensaje no respondido de un cliente, por día de la semana",
    "target {minutes}m": "objetivo {minutes}m",
    "This week:": "Esta semana:",
    "Last week:": "Semana pasada:",
    "No replies recorded yet": "Aún sin respuestas registradas",
    "This chart fills in as you reply to customer messages.": "Este gráfico se completa a medida que respondes a los mensajes de los clientes.",
    "Not enough data yet": "Aún no hay suficientes datos",

    # Inbox
    "WhatsApp® is not connected. Go to Settings to connect your account.": "WhatsApp® no está conectado. Ve a Configuración para conectar tu cuenta.",
    "Search conversations...": "Buscar conversaciones...",
    "All": "Todas",
    "Unread": "No leídas",
    "Open": "Abiertas",
    "Pending": "Pendientes",
    "Closed": "Cerradas",
    "Tags": "Etiquetas",
    "Company": "Empresa",
    "All companies": "Todas las empresas",
    "Clear all": "Limpiar todo",
    "No conversations found": "No se encontraron conversaciones",
    "No messages yet": "Aún sin mensajes",
    "Unknown": "Desconocido",
    "Back to conversations": "Volver a conversaciones",
    "Hide contact panel": "Ocultar panel de contacto",
    "Show contact panel": "Mostrar panel de contacto",
    "Hide contact": "Ocultar contacto",
    "Show contact": "Mostrar contacto",
    "Refresh": "Actualizar",
    "Refresh conversation": "Actualizar conversación",
    "Status": "Estado",
    "Assign": "Asignar",
    "Assigned": "Asignado",
    "Unassign": "Desasignar",
    "No teammates available": "No hay compañeros disponibles",
    " (me)": " (yo)",
    "Send a template to start the conversation": "Envía una plantilla para iniciar la conversación",
    "Select a conversation": "Selecciona una conversación",
    "Choose a conversation from the left to start messaging": "Elige una conversación de la izquierda para empezar a chatear",
    "Today": "Hoy",
    "Yesterday": "Ayer",
    "Expired": "Expirado",
    "{hours}h remaining": "{hours}h restantes",
    "{minutes}m remaining": "{minutes}m restantes",
    "No customer messages": "Sin mensajes del cliente",
    "Tap the ✨ to draft a reply with AI — you can edit it before sending": "Toca ✨ para redactar una respuesta con IA — puedes editarla antes de enviar",
    "24-hour session expired. Use a template to re-engage.": "Sesión de 24 horas expirada. Usa una plantilla para reconectar.",
    "Templates": "Plantillas",
    "Read-only — viewers can browse but not reply": "Solo lectura — los espectadores pueden ver pero no responder",
    "Session expired - use a template": "Sesión expirada - usa una plantilla",
    "Type a message... (Shift+Enter for new line)": "Escribe un mensaje... (Shift+Enter para nueva línea)",
    "Read-only — your role can't send messages": "Solo lectura — tu rol no puede enviar mensajes",
    "Recording… {current} / {max}": "Grabando… {current} / {max}",
    "Cancel": "Cancelar",
    "Stop and attach": "Detener y adjuntar",
    "Attach media": "Adjuntar archivo",
    "Photo": "Foto",
    "Video": "Video",
    "Document": "Documento",
    "Voice note": "Nota de voz",
    "Send template": "Enviar plantilla",
    "Draft a reply with AI": "Redactar respuesta con IA",
    "Add a caption…": "Añadir un pie de foto…",
    "Remove attachment": "Eliminar adjunto",
    "More": "Más",
    "Interactive message": "Mensaje interactivo",
    "Quick replies": "Respuestas rápidas",
    "No quick replies yet. Add some in Settings → Quick replies.": "Aún sin respuestas rápidas. Añádelas en Configuración → Respuestas rápidas.",
    "Save as quick reply": "Guardar como respuesta rápida",
    "Send": "Enviar",
    "Name this quick reply:": "Nombra esta respuesta rápida:",
    "Saved as a quick reply.": "Guardada como respuesta rápida.",
    "Couldn't save the quick reply.": "No se pudo guardar la respuesta rápida.",
    "Audio": "Audio",
    "{label} unavailable": "{label} no disponible",
    "Location shared": "Ubicación compartida",
    "Template": "Plantilla",
    "Button reply": "Respuesta de botón",
    "[Interactive reply]": "[Respuesta interactiva]",
    "[Unsupported message type]": "[Tipo de mensaje no soportado]",
    "AI": "IA",
    "Sent automatically by the AI assistant": "Enviado automáticamente por el asistente de IA",
    "Reply": "Responder",
    "Copy text": "Copiar texto",
    "Delete": "Eliminar",
    "React": "Reaccionar",
    "React with {emoji}": "Reaccionar con {emoji}",
    "Nothing to copy": "Nada que copiar",
    "Copied": "Copiado",
    "Copy failed": "Error al copiar",
    "[Photo]": "[Foto]",
    "[Video]": "[Video]",
    "[Document]": "[Documento]",
    "[Audio]": "[Audio]",
    "[Voice message]": "[Mensaje de voz]",
    "[Location]": "[Ubicación]",
    "[Message]": "[Mensaje]",
    "Cancel reply": "Cancelar respuesta",
    "Fill in the placeholders to render this template. Meta requires every variable to be set.": "Completa los marcadores para renderizar esta plantilla. Meta requiere que cada variable esté configurada.",
    "Pick an approved WhatsApp template to send to this contact.": "Elige una plantilla de WhatsApp aprobada para enviar a este contacto.",
    "No approved templates": "Sin plantillas aprobadas",
    "Approve a template in Meta WhatsApp Manager, then sync it from Settings → Templates.": "Aprueba una plantilla en Meta WhatsApp Manager, luego sincronízala desde Configuración → Plantillas.",
    "Preview": "Vista previa",
    "Value for the header variable": "Valor para la variable del encabezado",
    "Value for {val}": "Valor para {val}",
    "URL suffix value": "Valor del sufijo URL",
    "Final URL: {url}": "URL final: {url}",
    "Back": "Atrás",
    "Send template": "Enviar plantilla",
    "Contact info": "Información de contacto",
    "Notes": "Notas",
    "Deals": "Negocios",
    "No tags": "Sin etiquetas",
    "No deals": "Sin negocios",
    "Add a note...": "Añadir una nota...",
    "AI assistant is paused here": "El asistente de IA está pausado aquí",
    "AI assistant is replying automatically": "El asistente de IA está respondiendo automáticamente",
    "Take over": "Tomar control",
    "Resume AI": "Reanudar IA",
    "You've taken over this chat.": "Has tomado el control de este chat.",
    "AI resumed.": "IA reanudada.",
    "Couldn't update the AI assistant.": "No se pudo actualizar el asistente de IA.",
    "Couldn't reach the server.": "No se pudo conectar con el servidor.",

    # Contacts
    "Manage your contact list. {count} total contacts.": "Gestiona tu lista de contactos. {count} contactos en total.",
    "Manage your contact list.": "Gestiona tu lista de contactos.",
    "Custom fields": "Campos personalizados",
    "Import": "Importar",
    "Add Contact": "Añadir contacto",
    "Search by name, phone, or email...": "Buscar por nombre, teléfono o correo...",
    "Filter by tags": "Filtrar por etiquetas",
    "No tags yet.": "Aún sin etiquetas.",
    "{count} selected": "{count} seleccionados",
    "Clear": "Limpiar",
    "Delete selected": "Eliminar seleccionados",
    "Name": "Nombre",
    "Phone": "Teléfono",
    "Created": "Creado",
    "Loading contacts...": "Cargando contactos...",
    "No contacts match your filters.": "Ningún contacto coincide con tus filtros.",
    "No contacts yet.": "Aún sin contactos.",
    "Add your first contact": "Añade tu primer contacto",
    "Unnamed": "Sin nombre",
    "Edit": "Editar",
    "showing": "Mostrando",
    "Showing {start}-{end} of {total}": "Mostrando {start}-{end} de {total}",
    "Page {page} of {total}": "Página {page} de {total}",
    "Delete Contact": "Eliminar contacto",
    "Are you sure you want to delete {name}? This action cannot be undone.": "¿Estás seguro de que quieres eliminar a {name}? Esta acción no se puede deshacer.",
    "Delete Contacts": "Eliminar contactos",
    "Are you sure you want to delete {count} selected contacts? This action cannot be undone.": "¿Estás seguro de que quieres eliminar {count} contactos seleccionados? Esta acción no se puede deshacer.",
    "Failed to load contacts": "Error al cargar contactos",
    "Failed to delete contact": "Error al eliminar contacto",
    "Contact deleted": "Contacto eliminado",
    "Failed to delete contacts": "Error al eliminar contactos",
    "{count} contacts deleted": "{count} contactos eliminados",
    "Create a new contact. Name is required.": "Crea un nuevo contacto. El nombre es obligatorio.",
    "Edit Contact": "Editar contacto",
    "Update contact details and tags.": "Actualiza los detalles y etiquetas del contacto.",
    "Phone Number": "Número de teléfono",
    "Include country code, e.g. +1 for US": "Incluye código de país, ej. +52 para México",
    "jane@example.com": "jane@ejemplo.com",
    "Acme Corp": "Acme Corp",
    "Select tags...": "Seleccionar etiquetas...",
    "No tags found.": "No se encontraron etiquetas.",
    "Create tag \"{value}\"": "Crear etiqueta \"{value}\"",
    "Save Contact": "Guardar contacto",
    "Update": "Actualizar",
    "Create": "Crear",
    "Contact created successfully": "Contacto creado correctamente",
    "Contact updated successfully": "Contacto actualizado correctamente",
    "Failed to save contact": "Error al guardar el contacto",
    "A contact with this phone number already exists": "Ya existe un contacto con este número de teléfono",
    "View {name}": "Ver {name}",
    "A contact with this phone number already exists.": "Ya existe un contacto con este número de teléfono.",
    "A contact with a very similar number already exists.": "Ya existe un contacto con un número muy similar.",
    "Loading tags...": "Cargando etiquetas...",
    "No tags available. Create tags in Settings.": "No hay etiquetas disponibles. Crea etiquetas en Configuración.",
    "Phone number is required": "El número de teléfono es obligatorio",
    "Details": "Detalles",
    "Activity": "Actividad",
    "Custom Fields": "Campos personalizados",
    "Contact Information": "Información de contacto",
    "Contact details": "Detalles del contacto",
    "Created At": "Creado el",
    "No custom fields defined. Create them in Settings.": "No hay campos personalizados definidos. Créalos en Configuración.",
    "Manage fields": "Gestionar campos",
    "Enter {name}...": "Ingresa {name}...",
    "Activity History": "Historial de actividad",
    "Internal Notes": "Notas internas",
    "Write a note...": "Escribe una nota...",
    "Add Note": "Añadir nota",
    "No notes yet.": "Aún sin notas.",
    "No deals yet": "Aún sin negocios",
    "Click a tag to add or remove it from this contact.": "Haz clic en una etiqueta para añadirla o quitarla de este contacto.",
    "No tags available. Create tags in Settings.": "No hay etiquetas disponibles. Crea etiquetas en Configuración.",
    "Send template": "Enviar plantilla",
    "Save Changes": "Guardar cambios",
    "Save Custom Fields": "Guardar campos personalizados",
    "Phone number is required": "El número de teléfono es obligatorio",
    "Failed to update contact": "Error al actualizar el contacto",
    "Contact updated": "Contacto actualizado",
    "Not authenticated": "No autenticado",
    "Failed to add note": "Error al añadir nota",
    "Note added": "Nota añadida",
    "Failed to delete note": "Error al eliminar nota",
    "Note deleted": "Nota eliminada",
    "Custom fields saved": "Campos personalizados guardados",
    "Failed to save custom fields": "Error al guardar campos personalizados",
    "Template \"{name}\" sent": "Plantilla \"{name}\" enviada",
    "Failed to send template: {reason}": "Error al enviar plantilla: {reason}",

    # Import Modal
    "Import Contacts": "Importar contactos",
    'Upload a CSV with a required <phoneCode>phone</phoneCode> column. Optional: <nameCode>name</nameCode>, <emailCode>email</emailCode>, <companyCode>company</companyCode>, <tagsCode>tags</tagsCode> (comma-separated; quote multi-tag cells).': 'Sube un CSV con una columna <phoneCode>phone</phoneCode> obligatoria. Opcionales: <nameCode>name</nameCode>, <emailCode>email</emailCode>, <companyCode>company</companyCode>, <tagsCode>tags</tagsCode> (separados por comas; entrecomilla celdas con múltiples etiquetas).',
    "Click to choose a CSV file": "Haz clic para elegir un archivo CSV",
    ".csv up to your browser limit": ".csv hasta el límite de tu navegador",
    "{count} row ready": "{count} fila lista",
    "{count} rows ready": "{count} filas listas",
    "Preview · first {count}": "Vista previa · primeras {count}",
    "{tags} tag · {contacts} contact": "{tags} etiqueta · {contacts} contacto",
    "{tags} tags · {contacts} contacts": "{tags} etiquetas · {contacts} contactos",
    "+ {count} more row not shown": "+ {count} fila más no mostrada",
    "+ {count} more rows not shown": "+ {count} filas más no mostradas",
    "Import complete": "Importación completada",
    "{count} imported": "{count} importados",
    "{count} tag assigned": "{count} etiqueta asignada",
    "{count} tags assigned": "{count} etiquetas asignadas",
    "{count} skipped": "{count} omitidos",
    "{count} failed": "{count} fallidos",
    "{name} (will be created on import)": "{name} (se creará al importar)",
    "Close": "Cerrar",
    "Import {count} contact": "Importar {count} contacto",
    "Import {count} contacts": "Importar {count} contactos",
    'No valid rows found. Ensure CSV has a "phone" column header.': 'No se encontraron filas válidas. Asegúrate de que el CSV tenga un encabezado "phone".',
    "Contacts imported, but some tag assignments failed.": "Contactos importados, pero algunas asignaciones de etiquetas fallaron.",
    "{count} contact imported": "{count} contacto importado",
    "{count} contacts imported": "{count} contactos importados",
    "{count} tag assignment applied": "{count} asignación de etiqueta aplicada",
    "{count} tag assignments applied": "{count} asignaciones de etiquetas aplicadas",
    "Unknown tags skipped (create them in Settings first): {sample}{more}": "Etiquetas desconocidas omitidas (críalas primero en Configuración): {sample}{more}",
    "{count} duplicate skipped": "{count} duplicado omitido",
    "{count} duplicates skipped": "{count} duplicados omitidos",
    "{count} contact failed to import": "{count} contacto falló al importar",
    "{count} contacts failed to import": "{count} contactos fallaron al importar",
    "Import failed": "Importación fallida",
    "Define extra contact fields (e.g. ZIP code, lead source). They appear on every contact and in the \"Update Contact Field\" automation action.": "Define campos de contacto adicionales (ej. código postal, fuente del lead). Aparecen en cada contacto y en la acción de automatización \"Actualizar campo de contacto\".",
    "Add": "Añadir",
    "New field name…": "Nombre del nuevo campo…",
    "Loading…": "Cargando…",
    "No custom fields yet.": "Aún sin campos personalizados.",
    "Rename {name}": "Renombrar {name}",
    "Delete field": "Eliminar campo",
    'Delete "{name}"? This also removes its stored value on every contact. This cannot be undone.': '¿Eliminar "{name}"? Esto también elimina su valor almacenado en cada contacto. No se puede deshacer.',
    "Your profile is not linked to an account.": "Tu perfil no está vinculado a una cuenta.",
    'A field named "{name}" already exists.': 'Ya existe un campo llamado "{name}".',
    "Could not create field. You may not have permission.": "No se pudo crear el campo. Puede que no tengas permiso.",
    'Created "{name}".': 'Creado "{name}".',
    "Could not rename field.": "No se pudo renombrar el campo.",
    "Could not delete field.": "No se pudo eliminar el campo.",
    'Deleted "{name}".': 'Eliminado "{name}".',

    # Pipelines
    "Select Pipeline": "Seleccionar tubería",
    "No pipelines yet": "Aún sin tuberías",
    "Manage Pipelines": "Gestionar tuberías",
    "Add Pipeline": "Añadir tubería",
    "Add Deal": "Añadir negocio",
    "Create a pipeline to start tracking deals": "Crea una tubería para empezar a rastrear negocios",
    "Create Pipeline": "Crear tubería",
    "New Pipeline": "Nueva tubería",
    "Pipeline Name": "Nombre de la tubería",
    "e.g., Enterprise Sales": "ej., Ventas empresariales",
    "Default stages (New Lead → Won) will be created automatically.": "Las etapas por defecto (Nuevo lead → Ganado) se crearán automáticamente.",
    "Creating...": "Creando...",
    "Create Pipeline": "Crear tubería",
    "Failed to load pipelines": "Error al cargar tuberías",
    "Failed to move deal": "Error al mover negocio",
    "Failed to create pipeline": "Error al crear tubería",
    "Pipeline created": "Tubería creada",
    "Your profile is not linked to an account.": "Tu perfil no está vinculado a una cuenta.",
    "Drop a deal here": "Suelta un negocio aquí",
    "Add Deal": "Añadir negocio",

    # Broadcasts
    "Create Broadcast": "Crear transmisión",
    "Broadcast": "Transmisión",
    "Broadcasts": "Transmisiones",
    "New Broadcast": "Nueva transmisión",
    "Broadcast Name": "Nombre de la transmisión",
    "e.g., Holiday Promotion": "ej., Promoción navideña",
    "Template to Send": "Plantilla a enviar",
    "Select a template": "Seleccionar una plantilla",
    "No templates available. Create one in Meta WhatsApp Manager first.": "No hay plantillas disponibles. Crea una primero en Meta WhatsApp Manager.",
    "Target Audience": "Audiencia objetivo",
    "All contacts": "Todos los contactos",
    "Filter by tags": "Filtrar por etiquetas",
    "No tags created yet.": "Aún no se han creado etiquetas.",
    "Schedule": "Programar",
    "Send now": "Enviar ahora",
    "Schedule for later": "Programar para después",
    "Scheduled Date": "Fecha programada",
    "Scheduled Time": "Hora programada",
    "Preview Broadcast": "Vista previa de transmisión",
    "Recipients: ~{count}": "Destinatarios: ~{count}",
    "Send Broadcast": "Enviar transmisión",
    "Saving...": "Guardando...",
    "Sending...": "Enviando...",
    "Broadcast saved": "Transmisión guardada",
    "Broadcast sent": "Transmisión enviada",
    "Failed to save broadcast": "Error al guardar transmisión",
    "Failed to send broadcast": "Error al enviar transmisión",
    "No broadcasts yet": "Aún sin transmisiones",
    "Create your first broadcast": "Crea tu primera transmisión",
    "Sent": "Enviada",
    "Draft": "Borrador",
    "Scheduled": "Programada",
    "Failed": "Fallida",
    "Status": "Estado",
    "Recipients": "Destinatarios",
    "Delivered": "Entregados",
    "Read": "Leídos",
    "Click to view": "Haz clic para ver",
    "Delete Broadcast": "Eliminar transmisión",
    "Are you sure you want to delete \"{name}\"?": "¿Estás seguro de que quieres eliminar \"{name}\"?",

    # Automations
    "Automations": "Automatizaciones",
    "New Automation": "Nueva automatización",
    "No automations yet": "Aún sin automatizaciones",
    "Create your first automation": "Crea tu primera automatización",
    "Automation Name": "Nombre de la automatización",
    "e.g., Welcome Message": "ej., Mensaje de bienvenida",
    "Trigger": "Disparador",
    "When a tag is added": "Cuando se añade una etiqueta",
    "When a deal stage changes": "Cuando cambia la etapa de un negocio",
    "When a contact is created": "Cuando se crea un contacto",
    "When a contact sends a message": "Cuando un contacto envía un mensaje",
    "Condition": "Condición",
    "Has tag": "Tiene etiqueta",
    "Has deal in stage": "Tiene negocio en etapa",
    "Action": "Acción",
    "Send a template": "Enviar una plantilla",
    "Update contact field": "Actualizar campo de contacto",
    "Update deal stage": "Actualizar etapa del negocio",
    "Assign to teammate": "Asignar a compañero",
    "Add to automation": "Añadir a automatización",
    "Save Automation": "Guardar automatización",
    "Automation saved": "Automatización guardada",
    "Failed to save automation": "Error al guardar automatización",
    "Delete Automation": "Eliminar automatización",
    "Are you sure you want to delete \"{name}\"?": "¿Estás seguro de que quieres eliminar \"{name}\"?",
    "Active": "Activo",
    "Inactive": "Inactivo",
    "Toggle": "Alternar",
    "trigger": "disparador",
    "condition": "condición",
    "action": "acción",

    # Settings
    "Settings": "Configuración",
    "General": "General",
    "Profile": "Perfil",
    "Account": "Cuenta",
    "Team": "Equipo",
    "API Keys": "Claves API",
    "WhatsApp": "WhatsApp",
    "Templates": "Plantillas",
    "Quick replies": "Respuestas rápidas",
    "Tags": "Etiquetas",
    "Billing": "Facturación",
    "AI Assistant": "Asistente de IA",
    "General Settings": "Configuración general",
    "Company Name": "Nombre de la empresa",
    "Company Logo": "Logo de la empresa",
    "Default Language": "Idioma predeterminado",
    "Save Settings": "Guardar configuración",
    "Settings saved": "Configuración guardada",
    "Failed to save settings": "Error al guardar configuración",
    "Connected": "Conectado",
    "Disconnected": "Desconectado",
    "Connect WhatsApp": "Conectar WhatsApp",
    "Disconnect": "Desconectar",
    "WhatsApp Business Account": "Cuenta de WhatsApp Business",
    "Phone Number ID": "ID de número de teléfono",
    "Business Account ID": "ID de cuenta de negocio",
    "Webhook URL": "URL del webhook",
    "Webhook Status": "Estado del webhook",
    "Verify Token": "Token de verificación",
    "Copy": "Copiar",
    "Copied!": "¡Copiado!",
    "Connection Instructions": "Instrucciones de conexión",
    "Step 1": "Paso 1",
    "Step 2": "Paso 2",
    "Step 3": "Paso 3",
    "Go to Meta for Developers": "Ve a Meta for Developers",
    "Create or select your app": "Crea o selecciona tu aplicación",
    "Add the WhatsApp product": "Añade el producto WhatsApp",
    "Configure the webhook with the URL and token above": "Configura el webhook con la URL y el token de arriba",
    "Add your phone number": "Añade tu número de teléfono",
    "Generate a token": "Genera un token",
    "Paste the token below": "Pega el token abajo",
    "Access Token": "Token de acceso",
    "Save Token": "Guardar token",
    "Token saved": "Token guardado",
    "Failed to save token": "Error al guardar token",
    "Team Members": "Miembros del equipo",
    "Invite Member": "Invitar miembro",
    "Invite via Email": "Invitar por correo",
    "Email address": "Dirección de correo",
    "Role": "Rol",
    "Invite": "Invitar",
    "Invitation sent": "Invitación enviada",
    "Failed to send invitation": "Error al enviar invitación",
    "Remove Member": "Eliminar miembro",
    "Are you sure you want to remove {name}?": "¿Estás seguro de que quieres eliminar a {name}?",
    "Member removed": "Miembro eliminado",
    "Failed to remove member": "Error al eliminar miembro",
    "No team members yet": "Aún sin miembros del equipo",
    "API Keys": "Claves API",
    "Create API Key": "Crear clave API",
    "Key Name": "Nombre de la clave",
    "Key created": "Clave creada",
    "Copy this key now. You won't be able to see it again.": "Copia esta clave ahora. No podrás verla de nuevo.",
    "Revoke": "Revocar",
    "Revoke Key": "Revocar clave",
    "Are you sure you want to revoke \"{name}\"?": "¿Estás seguro de que quieres revocar \"{name}\"?",
    "Key revoked": "Clave revocada",
    "No API keys yet": "Aún sin claves API",
    "Template Management": "Gestión de plantillas",
    "Sync Templates": "Sincronizar plantillas",
    "Templates synced": "Plantillas sincronizadas",
    "Failed to sync templates": "Error al sincronizar plantillas",
    "No templates yet": "Aún sin plantillas",
    "Status: Approved": "Estado: Aprobada",
    "Status: Pending": "Estado: Pendiente",
    "Status: Rejected": "Estado: Rechazada",
    "Quick Replies": "Respuestas rápidas",
    "Add Quick Reply": "Añadir respuesta rápida",
    "Shortcut": "Atajo",
    "Message": "Mensaje",
    "Shortcut placeholder": "ej., gracias",
    "Message placeholder": "¡Gracias por contactarnos!",
    "Quick reply added": "Respuesta rápida añadida",
    "Quick reply deleted": "Respuesta rápida eliminada",
    "Failed to add quick reply": "Error al añadir respuesta rápida",
    "Delete quick reply": "Eliminar respuesta rápida",
    "Are you sure?": "¿Estás seguro?",
    "Manage Tags": "Gestionar etiquetas",
    "Create Tag": "Crear etiqueta",
    "Tag Name": "Nombre de la etiqueta",
    "Color": "Color",
    "Tag created": "Etiqueta creada",
    "Tag deleted": "Etiqueta eliminada",
    "Failed to create tag": "Error al crear etiqueta",
    "Delete tag": "Eliminar etiqueta",
    "Are you sure you want to delete \"{name}\"? This will remove it from all contacts.": "¿Estás seguro de que quieres eliminar \"{name}\"? Esto la eliminará de todos los contactos.",
    "AI Provider": "Proveedor de IA",
    "OpenAI": "OpenAI",
    "Anthropic": "Anthropic",
    "API Key": "Clave API",
    "Model": "Modelo",
    "Auto-reply": "Respuesta automática",
    "Enable auto-reply": "Activar respuesta automática",
    "Draft assistance": "Asistencia de borrador",
    "Enable draft suggestions": "Activar sugerencias de borrador",
    "AI settings saved": "Configuración de IA guardada",
    "Failed to save AI settings": "Error al guardar configuración de IA",

    # Flows
    "Flows": "Flujos",
    "New Flow": "Nuevo flujo",
    "No flows yet": "Aún sin flujos",
    "Create your first flow": "Crea tu primer flujo",
    "Flow Name": "Nombre del flujo",
    "e.g., Onboarding Flow": "ej., Flujo de onboarding",
    "Start node": "Nodo de inicio",
    "End node": "Nodo final",
    "Message": "Mensaje",
    "Condition": "Condición",
    "Wait": "Esperar",
    "Action": "Acción",
    "Add Node": "Añadir nodo",
    "Delete Node": "Eliminar nodo",
    "Flow saved": "Flujo guardado",
    "Failed to save flow": "Error al guardar flujo",
    "Delete Flow": "Eliminar flujo",
    "Are you sure you want to delete \"{name}\"?": "¿Estás seguro de que quieres eliminar \"{name}\"?",
    "Published": "Publicado",
    "Draft": "Borrador",
    "Runs": "Ejecuciones",
    "Successful": "Exitosas",
    "Failed": "Fallidas",
    "Total Runs": "Ejecuciones totales",

    # Common / Shared
    "Loading...": "Cargando...",
    "Error": "Error",
    "Success": "Éxito",
    "Save": "Guardar",
    "Saved": "Guardado",
    "Delete": "Eliminar",
    "Edit": "Editar",
    "Cancel": "Cancelar",
    "Confirm": "Confirmar",
    "Search": "Buscar",
    "Filter": "Filtrar",
    "Sort": "Ordenar",
    "Export": "Exportar",
    "Import": "Importar",
    "Download": "Descargar",
    "Upload": "Subir",
    "Yes": "Sí",
    "No": "No",
    "On": "Encendido",
    "Off": "Apagado",
    "Enabled": "Activado",
    "Disabled": "Desactivado",
    "Loading": "Cargando",
    "Optional": "Opcional",
    "Required": "Obligatorio",
    "more": "más",
    "View all": "Ver todo",
    "No data": "Sin datos",
    "Filter by": "Filtrar por",
    "Clear filters": "Limpiar filtros",
    "Something went wrong": "Algo salió mal",
    "Try again": "Intentar de nuevo",
    "Page not found": "Página no encontrada",
    "Go home": "Ir al inicio",
    "Unauthorized": "No autorizado",
    "Forbidden": "Prohibido",
    "Not found": "No encontrado",
    "Server error": "Error del servidor",
    "Network error": "Error de red",
    "Retry": "Reintentar",

    # Supabase Auth (from middleware.ts)
    "Sign up": "Registrarse",
    "Sign Up": "Registrarse",
    "Sign out": "Cerrar sesión",
    "Already have an account?": "¿Ya tienes una cuenta?",
    "Forgot your password?": "¿Olvidaste tu contraseña?",
    "Reset password": "Restablecer contraseña",
    "Send reset email": "Enviar correo de restablecimiento",
    "Check your email for the reset link": "Revisa tu correo para el enlace de restablecimiento",
    "Password reset email sent": "Correo de restablecimiento enviado",
    "New password": "Nueva contraseña",
    "Confirm password": "Confirmar contraseña",
    "Update password": "Actualizar contraseña",
    "Password updated": "Contraseña actualizada",
    "Failed to update password": "Error al actualizar contraseña",
    "Invalid email or password": "Correo o contraseña inválidos",
    "Too many requests. Try again later.": "Demasiadas solicitudes. Intenta de nuevo más tarde.",

    # Signup page
    "Create your account": "Crea tu cuenta",
    "Create an account to get started": "Crea una cuenta para empezar",
    "Full Name": "Nombre completo",
    "Full name": "Nombre completo",
    "Jane Doe": "Juan Pérez",
    "Confirm Password": "Confirmar contraseña",
    "Creating account...": "Creando cuenta...",
    "Already registered?": "¿Ya estás registrado?",
    "Sign in": "Iniciar sesión",

    # Forgot password
    "Forgot Password": "Olvidé mi contraseña",
    "Enter your email and we'll send you a reset link.": "Ingresa tu correo y te enviaremos un enlace de restablecimiento.",
    "Send reset link": "Enviar enlace de restablecimiento",
    "Remember your password?": "¿Recuerdas tu contraseña?",
    "Back to sign in": "Volver a iniciar sesión",

    # Join / Invitation
    "Accept Invitation": "Aceptar invitación",
    "You've been invited to join": "Has sido invitado a unirte",
    "Accept": "Aceptar",
    "Decline": "Rechazar",
    "Invitation expired": "Invitación expirada",
    "Invalid invitation": "Invitación inválida",
}

def translate_value(value):
    """Translate a string value, preserving ICU plurals and variables."""
    if not isinstance(value, str):
        return value
    
    # Direct lookup first
    if value in translations:
        return translations[value]
    
    # Try to handle ICU plural patterns inside values
    # e.g., "{count} {count, plural, =1 {deal} other {deals}}"
    # These need the variable names preserved but the human text translated
    
    # Check if it contains ICU plural patterns
    icu_pattern = re.compile(r'(\{[^}]+\})')
    parts = icu_pattern.split(value)
    
    translated_parts = []
    for part in parts:
        if part.startswith('{') and part.endswith('}'):
            # This is a variable or ICU expression - keep it intact
            translated_parts.append(part)
        else:
            if part in translations:
                translated_parts.append(translations[part])
            else:
                translated_parts.append(part)
    
    result = ''.join(translated_parts)
    if result != value:
        return result
    
    # Last resort: with the key path context, just return original
    # (will be flagged as untranslated but won't crash)
    print(f"  [UNTRANSLATED] '{value}'")
    return value


def translate_obj(obj, path=""):
    """Recursively translate all string values in the JSON structure."""
    if isinstance(obj, dict):
        return {k: translate_obj(v, f"{path}.{k}") for k, v in obj.items()}
    elif isinstance(obj, list):
        return [translate_obj(item, f"{path}[{i}]") for i, item in enumerate(obj)]
    elif isinstance(obj, str):
        return translate_value(obj)
    else:
        return obj


# First try: directly translate using the dict
print("Translating en.json to es.json...")
es = translate_obj(en)

# Check for untranslated strings
untranslated = []
def find_untranslated(obj, path=""):
    if isinstance(obj, dict):
        for k, v in obj.items():
            find_untranslated(v, f"{path}.{k}")
    elif isinstance(obj, str):
        if obj in translations:
            pass  # known
        elif obj.startswith("{") and obj.endswith("}"):
            pass  # placeholder
        elif re.match(r'^\{?\{[^}]+\}\}?$', obj):
            pass  # placeholder
        else:
            # Check if it was translated
            pass

# Write es.json
dest = Path("/home/diegol/Documentos/wacrm/messages/es.json")
dest.write_text(json.dumps(es, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

# Verify structure
es_loaded = json.loads(dest.read_text(encoding="utf-8"))
print(f"\n✅ Translation complete!")
print(f"   Source: {len(json.dumps(en, indent=2))} chars / {len(str(json.dumps(list(en.keys()))))} top-level sections")
print(f"   Target: {len(json.dumps(es_loaded, indent=2))} chars")
print(f"   Top-level keys: {list(es_loaded.keys())}")

# Quick stats
src_str = json.dumps(en)
tgt_str = json.dumps(es_loaded)
print(f"\n   Total source characters: {len(src_str)}")
print(f"   Total target characters: {len(tgt_str)}")
print(f"   Strings translated: {sum(len(json.dumps(v)) for v in translations.values() if isinstance(v, str))} chars of translations")
