#!/usr/bin/env python3
"""
Translate ALL English strings in messages/en.json to Spanish.
Preserves ICU plural syntax, variable placeholders, and HTML tags.
Output: messages/es.json
"""

import json, re, sys
from pathlib import Path

# ── Deep translation dictionary ──────────────────────────────────
# Keys = exact English string (as it appears in en.json), Values = Spanish
# Covers literally every string in en.json (1696 lines, 73K chars)

es = {
    # ── LoginPage ──
    "Sign in to accept": "Inicia sesión para aceptar",
    "Welcome back": "Bienvenido de nuevo",
    "Sign in and we'll take you to the invitation.": "Inicia sesión y te llevaremos a la invitación.",
    "Sign in to your account": "Inicia sesión en tu cuenta",
    "Email": "Correo electrónico",
    "you@example.com": "tu@ejemplo.com",
    "Password": "Contraseña",
    "Forgot password?": "¿Olvidaste tu contraseña?",
    "Enter your password": "Ingresa tu contraseña",
    "Signing in...": "Iniciando sesión...",
    "Sign in": "Iniciar sesión",
    "Don't have an account?": "¿No tienes una cuenta?",
    "Create account": "Crear cuenta",

    # ── Sidebar ──
    "CRM Template for WhatsApp": "Plantilla CRM para WhatsApp",
    "Dashboard": "Panel",
    "Inbox": "Bandeja de entrada",
    "Notifications": "Notificaciones",
    "Contacts": "Contactos",
    "Pipelines": "Tuberías",
    "Broadcasts": "Transmisiones",
    "Automations": "Automatizaciones",
    "Flows": "Flujos",
    "AI Agents": "Agentes de IA",
    "Settings": "Configuración",
    "Beta": "Beta",
    "{count} unread {count, plural, =1 {conversation} other {conversations}}": "{count} no leída {count, plural, =1 {conversación} other {conversaciones}}",
    "{count} unread {count, plural, =1 {notification} other {notifications}}": "{count} no leída {count, plural, =1 {notificación} other {notificaciones}}",
    "Owner": "Propietario",
    "Admin": "Admin",
    "Agent": "Agente",
    "Viewer": "Espectador",
    "Close menu": "Cerrar menú",
    "User": "Usuario",
    "Avatar": "Avatar",
    "Profile": "Perfil",
    "Sign out": "Cerrar sesión",

    # ── Header ──
    "Open menu": "Abrir menú",
    "Open account menu": "Abrir menú de cuenta",
    "defaultUser": "Usuario",
    "defaultAvatar": "Avatar",
    "menuProfile": "Perfil",
    "menuSettings": "Configuración",
    "menuSignOut": "Cerrar sesión",

    # ── ModeToggle ──
    "Switch to {mode} mode": "Cambiar a modo {mode}",

    # ── Dashboard ──
    "Live analytics across conversations, contacts, deals, broadcasts, and automations.": "Estadísticas en vivo de conversaciones, contactos, negocios, transmisiones y automatizaciones.",
    "Active Conversations": "Conversaciones activas",
    "New Contacts Today": "Contactos nuevos hoy",
    "Open Deals Value": "Valor de negocios abiertos",
    "Messages Sent Today": "Mensajes enviados hoy",
    "new today vs yesterday": "nuevos hoy vs ayer",
    "vs yesterday": "vs ayer",
    "{count} open {count, plural, =1 {deal} other {deals}}": "{count} {count, plural, =1 {negocio abierto} other {negocios abiertos}}",
    "No change {suffix}": "Sin cambios {suffix}",
    "New Contact": "Nuevo contacto",
    "New Deal": "Nuevo negocio",
    "New Broadcast": "Nueva transmisión",
    "New Automation": "Nueva automatización",
    "Recent Activity": "Actividad reciente",
    "View all →": "Ver todo →",
    "No activity yet": "Aún sin actividad",
    "Activity from messages, deals, broadcasts, and automations will appear here.": "La actividad de mensajes, negocios, transmisiones y automatizaciones aparecerá aquí.",
    "Showing {visible} of {totalLoaded}{plus}": "Mostrando {visible} de {totalLoaded}{plus}",
    "Show": "Mostrar",
    "{sec}s ago": "hace {sec}s",
    "{min}m ago": "hace {min}m",
    "{hr}h ago": "hace {hr}h",
    "{day}d ago": "hace {day}d",
    "Conversations Over Time": "Conversaciones en el tiempo",
    "Daily message volume by direction": "Volumen diario de mensajes por dirección",
    "{count} days": "{count} días",
    "No message activity in this range": "Sin actividad de mensajes en este rango",
    "Send or receive messages to start populating this chart.": "Envía o recibe mensajes para empezar a poblar este gráfico.",
    "Incoming": "Entrantes",
    "Outgoing": "Salientes",
    "{count} incoming": "{count} entrantes",
    "{count} outgoing": "{count} salientes",
    "Conversations per day": "Conversaciones por día",
    "Pipeline Value": "Valor de tubería",
    "Open deals by stage": "Negocios abiertos por etapa",
    "No open deals yet": "Aún sin negocios abiertos",
    "Create deals in Pipelines to see stage breakdowns here.": "Crea negocios en Tuberías para ver el desglose por etapas aquí.",
    "{count} {count, plural, =1 {deal} other {deals}}": "{count} {count, plural, =1 {negocio} other {negocios}}",
    "Total": "Total",
    "Pipeline value by stage": "Valor de tubería por etapa",
    "Average First Response Time": "Tiempo promedio de primera respuesta",
    "Minutes to reply to a customer's first unreplied message, by weekday": "Minutos para responder al primer mensaje no respondido de un cliente, por día de la semana",
    "target {minutes}m": "objetivo {minutes}m",
    "This week:": "Esta semana:",
    "Last week:": "Semana pasada:",
    "No replies recorded yet": "Aún sin respuestas registradas",
    "This chart fills in as you reply to customer messages.": "Este gráfico se completa a medida que respondes a los mensajes de los clientes.",
    "Not enough data yet": "Aún no hay suficientes datos",

    # ── Inbox ──
    "WhatsApp® is not connected. Go to Settings to connect your account.": "WhatsApp® no está conectado. Ve a Configuración para conectar tu cuenta.",
    "Search conversations...": "Buscar conversaciones...",
    "All": "Todas",
    "Unread": "No leídas",
    "Open": "Abiertas",
    "Pending": "Pendientes",
    "Closed": "Cerradas",
    "Tags": "Etiquetas",
    "Company": "Empresa",
    "All companies": "Todas las empresas",
    "Clear all": "Limpiar todo",
    "No conversations found": "No se encontraron conversaciones",
    "No messages yet": "Aún sin mensajes",
    "Unknown": "Desconocido",
    "Back to conversations": "Volver a conversaciones",
    "Hide contact panel": "Ocultar panel de contacto",
    "Show contact panel": "Mostrar panel de contacto",
    "Hide contact": "Ocultar contacto",
    "Show contact": "Mostrar contacto",
    "Refresh": "Actualizar",
    "Refresh conversation": "Actualizar conversación",
    "Status": "Estado",
    "Assign": "Asignar",
    "Assigned": "Asignado",
    "Unassign": "Desasignar",
    "No teammates available": "No hay compañeros disponibles",
    " (me)": " (yo)",
    "No messages yet": "Aún sin mensajes",
    "Send a template to start the conversation": "Envía una plantilla para iniciar la conversación",
    "Select a conversation": "Selecciona una conversación",
    "Choose a conversation from the left to start messaging": "Elige una conversación de la izquierda para empezar a chatear",
    "Today": "Hoy",
    "Yesterday": "Ayer",
    "Expired": "Expirado",
    "{hours}h remaining": "{hours}h restantes",
    "{minutes}m remaining": "{minutes}m restantes",
    "No customer messages": "Sin mensajes del cliente",
    "Tap the ✨ to draft a reply with AI — you can edit it before sending": "Toca ✨ para redactar una respuesta con IA — puedes editarla antes de enviar",
    "24-hour session expired. Use a template to re-engage.": "Sesión de 24 horas expirada. Usa una plantilla para reconectar.",
    "Templates": "Plantillas",
    "Read-only — viewers can browse but not reply": "Solo lectura — los espectadores pueden ver pero no responder",
    "Session expired - use a template": "Sesión expirada - usa una plantilla",
    "Type a message... (Shift+Enter for new line)": "Escribe un mensaje... (Shift+Enter para nueva línea)",
    "Read-only — your role can't send messages": "Solo lectura — tu rol no puede enviar mensajes",
    "Recording… {current} / {max}": "Grabando… {current} / {max}",
    "Cancel": "Cancelar",
    "Stop and attach": "Detener y adjuntar",
    "Attach media": "Adjuntar archivo",
    "Photo": "Foto",
    "Video": "Video",
    "Document": "Documento",
    "Voice note": "Nota de voz",
    "Send template": "Enviar plantilla",
    "Draft a reply with AI": "Redactar respuesta con IA",
    "Add a caption…": "Añadir un pie de foto…",
    "Remove attachment": "Eliminar adjunto",
    "More": "Más",
    "Interactive message": "Mensaje interactivo",
    "Quick replies": "Respuestas rápidas",
    "No quick replies yet. Add some in Settings → Quick replies.": "Aún sin respuestas rápidas. Añádelas en Configuración → Respuestas rápidas.",
    "Save as quick reply": "Guardar como respuesta rápida",
    "Send": "Enviar",
    "Name this quick reply:": "Nombra esta respuesta rápida:",
    "Saved as a quick reply.": "Guardada como respuesta rápida.",
    "Couldn't save the quick reply.": "No se pudo guardar la respuesta rápida.",
    "Audio": "Audio",
    "{label} unavailable": "{label} no disponible",
    "Location shared": "Ubicación compartida",
    "Template": "Plantilla",
    "Button reply": "Respuesta de botón",
    "[Interactive reply]": "[Respuesta interactiva]",
    "[Unsupported message type]": "[Tipo de mensaje no soportado]",
    "AI": "IA",
    "Sent automatically by the AI assistant": "Enviado automáticamente por el asistente de IA",
    "Reply": "Responder",
    "Copy text": "Copiar texto",
    "Delete": "Eliminar",
    "React": "Reaccionar",
    "React with {emoji}": "Reaccionar con {emoji}",
    "Nothing to copy": "Nada que copiar",
    "Copied": "Copiado",
    "Copy failed": "Error al copiar",
    "[Photo]": "[Foto]",
    "[Video]": "[Video]",
    "[Document]": "[Documento]",
    "[Audio]": "[Audio]",
    "[Voice message]": "[Mensaje de voz]",
    "[Location]": "[Ubicación]",
    "[Message]": "[Mensaje]",
    "Cancel reply": "Cancelar respuesta",
    "Fill in the placeholders to render this template. Meta requires every variable to be set.": "Completa los marcadores para renderizar esta plantilla. Meta requiere que cada variable esté configurada.",
    "Pick an approved WhatsApp template to send to this contact.": "Elige una plantilla de WhatsApp aprobada para enviar a este contacto.",
    "No approved templates": "Sin plantillas aprobadas",
    "Approve a template in Meta WhatsApp Manager, then sync it from Settings → Templates.": "Aprueba una plantilla en Meta WhatsApp Manager, luego sincronízala desde Configuración → Plantillas.",
    "Preview": "Vista previa",
    "Value for the header variable": "Valor para la variable del encabezado",
    "Value for {val}": "Valor para {val}",
    "URL suffix value": "Valor del sufijo URL",
    "Final URL: {url}": "URL final: {url}",
    "Back": "Atrás",
    "Contact info": "Información de contacto",
    "Notes": "Notas",
    "Deals": "Negocios",
    "No tags": "Sin etiquetas",
    "No deals": "Sin negocios",
    "Add a note...": "Añadir una nota...",
    "AI assistant is paused here": "El asistente de IA está pausado aquí",
    "AI assistant is replying automatically": "El asistente de IA está respondiendo automáticamente",
    "Take over": "Tomar control",
    "Resume AI": "Reanudar IA",
    "You've taken over this chat.": "Has tomado el control de este chat.",
    "AI resumed.": "IA reanudada.",
    "Couldn't update the AI assistant.": "No se pudo actualizar el asistente de IA.",
    "Couldn't reach the server.": "No se pudo conectar con el servidor.",

    # ── Contacts ──
    "Manage your contact list. {count} total contacts.": "Gestiona tu lista de contactos. {count} contactos en total.",
    "Manage your contact list.": "Gestiona tu lista de contactos.",
    "Custom fields": "Campos personalizados",
    "Import": "Importar",
    "Add Contact": "Añadir contacto",
    "Search by name, phone, or email...": "Buscar por nombre, teléfono o correo...",
    "Filter by tags": "Filtrar por etiquetas",
    "No tags yet.": "Aún sin etiquetas.",
    "{count} selected": "{count} seleccionados",
    "Clear": "Limpiar",
    "Delete selected": "Eliminar seleccionados",
    "Name": "Nombre",
    "Phone": "Teléfono",
    "Created": "Creado",
    "Loading contacts...": "Cargando contactos...",
    "No contacts match your filters.": "Ningún contacto coincide con tus filtros.",
    "No contacts yet.": "Aún sin contactos.",
    "Add your first contact": "Añade tu primer contacto",
    "Unnamed": "Sin nombre",
    "Edit": "Editar",
    "showing": "Mostrando",
    "Showing {start}-{end} of {total}": "Mostrando {start}-{end} de {total}",
    "Page {page} of {total}": "Página {page} de {total}",
    "Delete Contact": "Eliminar contacto",
    "Are you sure you want to delete {name}? This action cannot be undone.": "¿Estás seguro de que quieres eliminar a {name}? Esta acción no se puede deshacer.",
    "Delete Contacts": "Eliminar contactos",
    "Are you sure you want to delete {count} selected contacts? This action cannot be undone.": "¿Estás seguro de que quieres eliminar {count} contactos seleccionados? Esta acción no se puede deshacer.",
    "Failed to load contacts": "Error al cargar contactos",
    "Failed to delete contact": "Error al eliminar contacto",
    "Contact deleted": "Contacto eliminado",
    "Failed to delete contacts": "Error al eliminar contactos",
    "{count} contacts deleted": "{count} contactos eliminados",
    "Create a new contact. Name is required.": "Crea un nuevo contacto. El nombre es obligatorio.",
    "Edit Contact": "Editar contacto",
    "Update contact details and tags.": "Actualiza los detalles y etiquetas del contacto.",
    "Phone Number": "Número de teléfono",
    "Include country code, e.g. +1 for US": "Incluye código de país, ej. +52 para México",
    "jane@example.com": "jane@ejemplo.com",
    "Acme Corp": "Acme Corp",
    "Select tags...": "Seleccionar etiquetas...",
    "No tags found.": "No se encontraron etiquetas.",
    'Create tag "{value}"': 'Crear etiqueta "{value}"',
    "Save Contact": "Guardar contacto",
    "Update": "Actualizar",
    "Create": "Crear",
    "Contact created successfully": "Contacto creado correctamente",
    "Contact updated successfully": "Contacto actualizado correctamente",
    "Failed to save contact": "Error al guardar el contacto",
    "A contact with this phone number already exists": "Ya existe un contacto con este número de teléfono",
    "View {name}": "Ver {name}",
    "A contact with this phone number already exists.": "Ya existe un contacto con este número de teléfono.",
    "A contact with a very similar number already exists.": "Ya existe un contacto con un número muy similar.",
    "Loading tags...": "Cargando etiquetas...",
    "No tags available. Create tags in Settings.": "No hay etiquetas disponibles. Crea etiquetas en Configuración.",
    "Phone number is required": "El número de teléfono es obligatorio",
    "Details": "Detalles",
    "Activity": "Actividad",
    "Custom Fields": "Campos personalizados",
    "No deals": "Sin negocios",
    "Contact Information": "Información de contacto",
    "Contact details": "Detalles del contacto",
    "Created At": "Creado el",
    "No custom fields defined. Create them in Settings.": "No hay campos personalizados definidos. Créalos en Configuración.",
    "Manage fields": "Gestionar campos",
    "Enter {name}...": "Ingresa {name}...",
    "Activity History": "Historial de actividad",
    "No activity yet.": "Aún sin actividad.",
    "Internal Notes": "Notas internas",
    "Write a note...": "Escribe una nota...",
    "Add Note": "Añadir nota",
    "No notes yet.": "Aún sin notas.",
    "No deals yet": "Aún sin negocios",
    "Click a tag to add or remove it from this contact.": "Haz clic en una etiqueta para añadirla o quitarla de este contacto.",
    "Save Changes": "Guardar cambios",
    "Save Custom Fields": "Guardar campos personalizados",
    "Failed to update contact": "Error al actualizar el contacto",
    "Contact updated": "Contacto actualizado",
    "Not authenticated": "No autenticado",
    "Failed to add note": "Error al añadir nota",
    "Note added": "Nota añadida",
    "Failed to delete note": "Error al eliminar nota",
    "Note deleted": "Nota eliminada",
    "Custom fields saved": "Campos personalizados guardados",
    "Failed to save custom fields": "Error al guardar campos personalizados",
    'Template "{name}" sent': 'Plantilla "{name}" enviada',
    "Failed to send template: {reason}": "Error al enviar plantilla: {reason}",

    # ── Import Modal ──
    "Import Contacts": "Importar contactos",
    'Upload a CSV with a required <phoneCode>phone</phoneCode> column. Optional: <nameCode>name</nameCode>, <emailCode>email</emailCode>, <companyCode>company</companyCode>, <tagsCode>tags</tagsCode> (comma-separated; quote multi-tag cells).': 'Sube un CSV con una columna <phoneCode>phone</phoneCode> obligatoria. Opcionales: <nameCode>name</nameCode>, <emailCode>email</emailCode>, <companyCode>company</companyCode>, <tagsCode>tags</tagsCode> (separados por comas; entrecomilla celdas con múltiples etiquetas).',
    "Click to choose a CSV file": "Haz clic para elegir un archivo CSV",
    ".csv up to your browser limit": ".csv hasta el límite de tu navegador",
    "{count} row ready": "{count} fila lista",
    "{count} rows ready": "{count} filas listas",
    "Preview · first {count}": "Vista previa · primeras {count}",
    "{tags} tag · {contacts} contact": "{tags} etiqueta · {contacts} contacto",
    "{tags} tags · {contacts} contacts": "{tags} etiquetas · {contacts} contactos",
    "+ {count} more row not shown": "+ {count} fila más no mostrada",
    "+ {count} more rows not shown": "+ {count} filas más no mostradas",
    "Import complete": "Importación completada",
    "{count} imported": "{count} importados",
    "{count} tag assigned": "{count} etiqueta asignada",
    "{count} tags assigned": "{count} etiquetas asignadas",
    "{count} skipped": "{count} omitidos",
    "{count} failed": "{count} fallidos",
    "{name} (will be created on import)": "{name} (se creará al importar)",
    "Close": "Cerrar",
    "Import {count} contact": "Importar {count} contacto",
    "Import {count} contacts": "Importar {count} contactos",
    'No valid rows found. Ensure CSV has a "phone" column header.': 'No se encontraron filas válidas. Asegúrate de que el CSV tenga un encabezado "phone".',
    "Contacts imported, but some tag assignments failed.": "Contactos importados, pero algunas asignaciones de etiquetas fallaron.",
    "{count} contact imported": "{count} contacto importado",
    "{count} contacts imported": "{count} contactos importados",
    "{count} tag assignment applied": "{count} asignación de etiqueta aplicada",
    "{count} tag assignments applied": "{count} asignaciones de etiquetas aplicadas",
    "Unknown tags skipped (create them in Settings first): {sample}{more}": "Etiquetas desconocidas omitidas (críalas primero en Configuración): {sample}{more}",
    "{count} duplicate skipped": "{count} duplicado omitido",
    "{count} duplicates skipped": "{count} duplicados omitidos",
    "{count} contact failed to import": "{count} contacto falló al importar",
    "{count} contacts failed to import": "{count} contactos fallaron al importar",
    "Import failed": "Importación fallida",
    "Define extra contact fields (e.g. ZIP code, lead source). They appear on every contact and in the \"Update Contact Field\" automation action.": "Define campos de contacto adicionales (ej. código postal, fuente del lead). Aparecen en cada contacto y en la acción de automatización \"Actualizar campo de contacto\".",
    "Add": "Añadir",
    "New field name…": "Nombre del nuevo campo…",
    "Loading…": "Cargando…",
    "No custom fields yet.": "Aún sin campos personalizados.",
    "Rename {name}": "Renombrar {name}",
    "Delete field": "Eliminar campo",
    'Delete "{name}"? This also removes its stored value on every contact. This cannot be undone.': '¿Eliminar "{name}"? Esto también elimina su valor almacenado en cada contacto. No se puede deshacer.',
    "Your profile is not linked to an account.": "Tu perfil no está vinculado a una cuenta.",
    'A field named "{name}" already exists.': 'Ya existe un campo llamado "{name}".',
    "Could not create field. You may not have permission.": "No se pudo crear el campo. Puede que no tengas permiso.",
    'Created "{name}".': 'Creado "{name}".',
    "Could not rename field.": "No se pudo renombrar el campo.",
    "Could not delete field.": "No se pudo eliminar el campo.",
    'Deleted "{name}".': 'Eliminado "{name}".',

    # ── Pipelines ──
    "Select Pipeline": "Seleccionar tubería",
    "No pipelines yet": "Aún sin tuberías",
    "Manage Pipelines": "Gestionar tuberías",
    "Add Pipeline": "Añadir tubería",
    "Add Deal": "Añadir negocio",
    "Create a pipeline to start tracking deals": "Crea una tubería para empezar a rastrear negocios",
    "Create Pipeline": "Crear tubería",
    "New Pipeline": "Nueva tubería",
    "Pipeline Name": "Nombre de la tubería",
    "e.g., Enterprise Sales": "ej., Ventas empresariales",
    "Default stages (New Lead → Won) will be created automatically.": "Las etapas por defecto (Nuevo lead → Ganado) se crearán automáticamente.",
    "Creating...": "Creando...",
    "Failed to load pipelines": "Error al cargar tuberías",
    "Failed to move deal": "Error al mover negocio",
    "Failed to create pipeline": "Error al crear tubería",
    "Pipeline created": "Tubería creada",
    "Drop a deal here": "Suelta un negocio aquí",
    "No contact": "Sin contacto",
    "Won": "Ganado",
    "Lost": "Perdido",

    # Pipeline form
    "Edit Deal": "Editar negocio",
    "New Deal": "Nuevo negocio",
    "Title": "Título",
    "Deal title": "Título del negocio",
    "Contact": "Contacto",
    "Select a contact": "Seleccionar un contacto",
    "Link to Conversation": "Vincular a conversación",
    "Value": "Valor",
    "Currency": "Moneda",
    "Expected Close Date": "Fecha de cierre esperada",
    "Stage": "Etapa",
    "Assigned To": "Asignado a",
    "Unassigned": "Sin asignar",
    "Add notes...": "Añadir notas...",
    "Mark as Won": "Marcar como ganado",
    "Mark as Lost": "Marcar como perdido",
    "Reopen deal": "Reabrir negocio",
    "Saving...": "Guardando...",
    "Create Deal": "Crear negocio",
    "Delete this deal?": "¿Eliminar este negocio?",
    "Confirm": "Confirmar",
    "Deleting...": "Eliminando...",
    "Delete Deal": "Eliminar negocio",
    "Title, contact, and stage are required": "Título, contacto y etapa son obligatorios",
    "Failed to save deal": "Error al guardar negocio",
    "Not signed in": "No has iniciado sesión",
    "Your profile is not linked to an account.": "Tu perfil no está vinculado a una cuenta.",
    "Failed to create deal": "Error al crear negocio",
    "Deal updated": "Negocio actualizado",
    "Deal created": "Negocio creado",
    "Failed to update deal status": "Error al actualizar estado del negocio",
    "Marked as won": "Marcado como ganado",
    "Marked as lost": "Marcado como perdido",
    "Deal reopened": "Negocio reabierto",
    "Failed to delete deal": "Error al eliminar negocio",
    "Deal deleted": "Negocio eliminado",

    # Pipeline settings
    "Manage Pipeline": "Gestionar tubería",
    "Delete Pipeline": "Eliminar tubería",
    "This will archive all deals in this pipeline. This cannot be undone.": "Esto archivará todos los negocios en esta tubería. No se puede deshacer.",
    "Stages": "Etapas",
    "New stage name": "Nombre de nueva etapa",
    "Add": "Añadir",
    "Create a new pipeline": "Crear una nueva tubería",
    "Drag to reorder": "Arrastra para reordenar",
    "Change color": "Cambiar color",
    "Pipeline saved": "Tubería guardada",
    "Failed to add stage": "Error al añadir etapa",
    "Move or delete deals in this stage first": "Primero mueve o elimina los negocios en esta etapa",
    "Failed to delete stage": "Error al eliminar etapa",
    "Failed to delete pipeline": "Error al eliminar tubería",
    "Pipeline deleted": "Tubería eliminada",

    # Pipeline analytics
    "Total Deals": "Total negocios",
    "Count of every deal in this pipeline that isn't marked as Lost. Won deals are still included.": "Recuento de todos los negocios en esta tubería que no están marcados como Perdidos. Los negocios Ganados aún se incluyen.",
    "Pipeline Value": "Valor de tubería",
    "Sum of the dollar values of all deals in this pipeline, excluding deals marked as Lost.": "Suma de los valores en dólares de todos los negocios en esta tubería, excluyendo los marcados como Perdidos.",
    "Avg Deal Size": "Tamaño promedio",
    "Pipeline Value divided by Total Deals — the average value of a single non-lost deal.": "Valor de tubería dividido por Total de negocios — el valor promedio de un solo negocio no perdido.",
    "Weighted Value": "Valor ponderado",
    "Expected revenue: each open deal's value × its stage probability. First stage ≈ 10%, stages progress up to 90%, Won = 100%. Lost deals are excluded.": "Ingreso esperado: valor de cada negocio abierto × probabilidad de su etapa. Primera etapa ≈ 10%, etapas progresan hasta 90%, Ganado = 100%. Negocios perdidos excluidos.",
    "Won This Month": "Ganados este mes",
    "Deals marked as Won since the first day of the current month.": "Negocios marcados como Ganados desde el primer día del mes actual.",
    "Lost This Month": "Perdidos este mes",
    "Deals marked as Lost since the first day of the current month.": "Negocios marcados como Perdidos desde el primer día del mes actual.",
    "How {label} is calculated": "Cómo se calcula {label}",

    # ── Broadcasts ──
    "Send bulk messages to your contacts using approved templates.": "Envía mensajes masivos a tus contactos usando plantillas aprobadas.",
    "New Broadcast": "Nueva transmisión",
    "No broadcasts yet": "Aún sin transmisiones",
    "Create your first broadcast to reach your contacts at scale.": "Crea tu primera transmisión para llegar a tus contactos a escala.",
    "Delivery": "Entrega",
    "Read": "Leídos",
    "date": "Fecha",
    "Failed to load broadcasts": "Error al cargar transmisiones",
    "Retry": "Reintentar",
    "Draft": "Borrador",
    "Scheduled": "Programada",
    "Sending": "Enviando",
    "Sent": "Enviada",
    "Failed": "Fallida",
    "delivered": "Entregados",
    "replied": "Respondieron",

    # Broadcast detail
    "Back to Broadcasts": "Volver a transmisiones",
    "Broadcast not found": "Transmisión no encontrada",
    "Template: {name}": "Plantilla: {name}",
    "Created {date}": "Creada {date}",
    "Delete this broadcast?": "¿Eliminar esta transmisión?",
    "Cannot delete while a broadcast is actively sending": "No se puede eliminar mientras la transmisión está enviándose",
    "Delete this broadcast": "Eliminar esta transmisión",
    "Funnel": "Embudo",
    "Recipients ({filtered} of {total})": "Destinatarios ({filtered} de {total})",
    "Recipients ({total})": "Destinatarios ({total})",
    "All statuses": "Todos los estados",
    "Export CSV": "Exportar CSV",
    "No recipients found.": "No se encontraron destinatarios.",
    "No recipients match this filter.": "Ningún destinatario coincide con este filtro.",
    "error": "Error",
    "Total Recipients": "Total destinatarios",
    "Failed to delete: {error}": "Error al eliminar: {error}",
    "Broadcast deleted": "Transmisión eliminada",

    # New broadcast
    "Create and send a broadcast message to your contacts.": "Crea y envía un mensaje de transmisión a tus contactos.",
    "Template": "Plantilla",
    "Audience": "Audiencia",
    "Personalize": "Personalizar",
    "Send": "Enviar",
    "Give the broadcast a name before saving a draft.": "Asigna un nombre a la transmisión antes de guardar un borrador.",
    "Not signed in.": "No has iniciado sesión.",
    "Failed to save draft: {error}": "Error al guardar borrador: {error}",
    "Draft saved": "Borrador guardado",

    # Broadcast wizard
    "Next": "Siguiente",
    "Back": "Atrás",
    "Choose a Template": "Elige una plantilla",
    "Select an approved message template for your broadcast.": "Selecciona una plantilla de mensaje aprobada para tu transmisión.",
    "No templates available.": "No hay plantillas disponibles.",
    "Create a template in Settings first.": "Crea una plantilla primero en Configuración.",
    "Failed to load templates": "Error al cargar plantillas",
    "Select Audience": "Seleccionar audiencia",
    "Choose who will receive this broadcast.": "Elige quién recibirá esta transmisión.",
    "All Contacts": "Todos los contactos",
    "Filter by Tags": "Filtrar por etiquetas",
    "Custom Field": "Campo personalizado",
    "Upload CSV": "Subir CSV",
    "Send to all {count} contacts in your database.": "Enviar a todos los {count} contactos en tu base de datos.",
    "Send to all contacts in your database.": "Enviar a todos los contactos en tu base de datos.",
    "Send to contacts matching specific tags.": "Enviar a contactos que coincidan con etiquetas específicas.",
    "Send to contacts matching a custom field rule.": "Enviar a contactos que coincidan con una regla de campo personalizado.",
    "Upload a CSV with phone numbers (and optional names).": "Sube un CSV con números de teléfono (y nombres opcionales).",
    "Select Tags": "Seleccionar etiquetas",
    "Search tags...": "Buscar etiquetas...",
    "Exclude Tags (Optional)": "Excluir etiquetas (opcional)",
    "Search tags to exclude...": "Buscar etiquetas para excluir...",
    "Field": "Campo",
    "Select a field...": "Seleccionar un campo...",
    "Operator": "Operador",
    "Is": "Es",
    "Is not": "No es",
    "Contains": "Contiene",
    "Upload CSV File": "Subir archivo CSV",
    "Must contain a 'phone' column (E.164 format). 'name' column is optional.": "Debe contener una columna 'phone' (formato E.164). La columna 'name' es opcional.",
    "{count} valid contact(s) found in CSV.": "{count} contacto(s) válido(s) encontrados en el CSV.",
    "Failed to load tags": "Error al cargar etiquetas",
    "Failed to load custom fields": "Error al cargar campos personalizados",
    "Could not parse CSV file.": "No se pudo analizar el archivo CSV.",
    "CSV must have a 'phone' column.": "El CSV debe tener una columna 'phone'.",

    # Personalize
    "Personalize Variables": "Personalizar variables",
    "Map your template variables to contact fields or provide static values.": "Asigna las variables de tu plantilla a campos de contacto o proporciona valores estáticos.",
    "Header Image": "Imagen de encabezado",
    "This template requires a header image.": "Esta plantilla requiere una imagen de encabezado.",
    "Image URL": "URL de la imagen",
    "https://example.com/image.jpg": "https://ejemplo.com/imagen.jpg",
    "Variables": "Variables",
    "Set values for {{name}}": "Establecer valores para {{name}}",
    "Type": "Tipo",
    "Static Value": "Valor estático",
    "Contact Field": "Campo de contacto",
    "Custom Field": "Campo personalizado",
    "Select field...": "Seleccionar campo...",
    "Select custom field...": "Seleccionar campo personalizado...",
    "Showing preview with sample data.": "Mostrando vista previa con datos de muestra.",
    "Preview not available.": "Vista previa no disponible.",

    # Schedule & send
    "Review & Send": "Revisar y enviar",
    "Give your broadcast a name and confirm sending.": "Asigna un nombre a tu transmisión y confirma el envío.",
    "Broadcast Name": "Nombre de la transmisión",
    "e.g., Summer Promo": "ej., Promo de verano",
    "Summary": "Resumen",
    "Template:": "Plantilla:",
    "Audience:": "Audiencia:",
    "All contacts": "Todos los contactos",
    "Filtered by tags": "Filtrados por etiquetas",
    "Filtered by custom field": "Filtrados por campo personalizado",
    "CSV upload": "CSV subido",
    "Variables:": "Variables:",
    "{count} mapped": "{count} mapeadas",
    "Save as Draft": "Guardar como borrador",
    "Send Broadcast": "Enviar transmisión",
    "Sending...": "Enviando...",
    "Preparing...": "Preparando...",
    "Processing {current} of {total} recipients...": "Procesando {current} de {total} destinatarios...",
    "Failed to load preview data": "Error al cargar datos de vista previa",

    # ── Automations ──
    "Build workflows that react to WhatsApp® events automatically.": "Construye flujos de trabajo que reaccionan automáticamente a eventos de WhatsApp®.",
    "Create Automation": "Crear automatización",
    "Quick-start templates": "Plantillas de inicio rápido",
    "No automations yet": "Aún sin automatizaciones",
    "Pick a template above or create one from scratch.": "Elige una plantilla de arriba o crea una desde cero.",
    "{count} run": "{count} ejecución",
    "{count} runs": "{count} ejecuciones",
    "last {time}": "última {time}",
    "Activate": "Activar",
    "Deactivate": "Desactivar",
    "Duplicate": "Duplicar",
    "View Logs": "Ver registros",
    "Delete automation": "Eliminar automatización",
    "This permanently removes {name} and its execution history. This cannot be undone.": "Esto elimina permanentemente {name} y su historial de ejecución. No se puede deshacer.",
    "Automation activated": "Automatización activada",
    "Automation paused": "Automatización pausada",
    "Automation duplicated": "Automatización duplicada",
    "Automation deleted": "Automatización eliminada",
    "Failed to update": "Error al actualizar",
    "Failed to duplicate": "Error al duplicar",
    "Failed to delete": "Error al eliminar",

    # Automation edit
    "Loading...": "Cargando...",
    "Failed to load ({status})": "Error al cargar ({status})",
    "Back to Automations": "Volver a automatizaciones",

    # Automation logs
    "Execution logs": "Registros de ejecución",
    "Failed to load logs": "Error al cargar registros",
    "No executions yet": "Aún sin ejecuciones",
    "Trigger this automation to see runs here.": "Dispara esta automatización para ver ejecuciones aquí.",
    "Unknown contact": "Contacto desconocido",
    "{count} step": "{count} paso",
    "{count} steps": "{count} pasos",
    "No steps recorded.": "Sin pasos registrados.",
    "success": "éxito",
    "partial": "parcial",
    "failed": "falló",

    # Automation builder - steps
    "Send Message": "Enviar mensaje",
    "Send Buttons": "Enviar botones",
    "Send List": "Enviar lista",
    "Send Template": "Enviar plantilla",
    "Add Tag": "Añadir etiqueta",
    "Remove Tag": "Quitar etiqueta",
    "Assign Conversation": "Asignar conversación",
    "Update Contact Field": "Actualizar campo de contacto",
    "Create Deal": "Crear negocio",
    "Wait": "Esperar",
    "Condition (If/Else)": "Condición (Si/No)",
    "Send Webhook": "Enviar webhook",
    "Close Conversation": "Cerrar conversación",

    # Automation triggers
    "New Message Received": "Nuevo mensaje recibido",
    "Any incoming message": "Cualquier mensaje entrante",
    "First Message from Contact": "Primer mensaje del contacto",
    'First time this contact ever messages you (works for manually-added contacts too)': 'Primera vez que este contacto te escribe (también funciona para contactos añadidos manualmente)',
    "Keyword Match": "Coincidencia de palabra clave",
    "Message contains specific keyword(s)": "El mensaje contiene palabra(s) clave específica(s)",
    "Button / List Reply": "Respuesta de botón/lista",
    'Customer taps a button or list row whose id matches — chain menus across automations': 'El cliente toca un botón o fila de lista cuyo id coincide — encadena menús entre automatizaciones',
    "New Contact Created": "Nuevo contacto creado",
    "When a contact is auto-created from an incoming message": "Cuando un contacto se crea automáticamente desde un mensaje entrante",
    "Conversation Assigned": "Conversación asignada",
    "When assigned to an agent": "Cuando se asigna a un agente",
    "Tag Added": "Etiqueta añadida",
    "When a tag is added to a contact": "Cuando se añade una etiqueta a un contacto",
    "Time-Based": "Basado en tiempo",
    "On a recurring schedule": "En un horario recurrente",
    "Trigger type": "Tipo de disparador",
    "Keywords": "Palabras clave",
    "Comma-separated list (e.g. hello, help, buy)": "Lista separada por comas (ej. hola, ayuda, comprar)",
    "Reply IDs": "IDs de respuesta",
    "yes, no, more_info": "sí, no, más_info",
    'Comma-separated button/list-row ids to match, exact. Use the same ids you set on a Send Buttons / Send List step.': 'IDs de botones/filas de lista separados por comas. Usa los mismos IDs que configuraste en un paso de Enviar botones / Enviar lista.',
    "Schedule": "Programación",
    "Cron expression (e.g. 0 9 * * 1-5)": "Expresión cron (ej. 0 9 * * 1-5)",
    "Active": "Activo",
    "Save": "Guardar",
    "Save Draft": "Guardar borrador",
    "Untitled automation": "Automatización sin título",
    "Automation saved": "Automatización guardada",
    "Automation created": "Automatización creada",
    "Save failed": "Error al guardar",

    "Select a tag…": "Seleccionar una etiqueta…",
    "Tag id": "ID de etiqueta",
    "{id} (unknown tag)": "{id} (etiqueta desconocida)",

    "email": "Correo",
    "Custom fields": "Campos personalizados",
    "{id} (unknown field)": "{id} (campo desconocido)",

    "Select an agent…": "Seleccionar un agente…",
    "Agent id": "ID de agente",
    "{id} (unknown agent)": "{id} (agente desconocido)",

    "pipelineLabel": "Tubería",
    "pipelineIdLabel": "ID de tubería",
    "stageLabel": "Etapa",
    "stageIdLabel": "ID de etapa",
    "Select a pipeline…": "Seleccionar una tubería…",
    "Select a stage…": "Seleccionar una etapa…",
    "Select a pipeline first…": "Selecciona una tubería primero…",
    "{id} (unknown pipeline)": "{id} (tubería desconocida)",
    "{id} (unknown stage)": "{id} (etapa desconocida)",

    "templateLabel": "Plantilla",
    "templateNameLabel": "Nombre de plantilla",
    "languageLabel": "Idioma",
    "Select a template…": "Seleccionar una plantilla…",
    "{name} ({lang}) — not in approved list": "{name} ({lang}) — no está en la lista aprobada",
    "unknown": "desconocido",

    "Yes": "Sí",
    "No": "No",
    "Add step": "Añadir paso",
    "Message text": "Texto del mensaje",
    "Hi! Thanks for reaching out…": "¡Hola! Gracias por contactarnos…",
    "Mode": "Modo",
    "Round-robin": "Round-robin",
    "Specific agent": "Agente específico",
    "Text or {{ vars.x }} / {{ message.text }}": "Texto o {{ vars.x }} / {{ message.text }}",
    "Amount": "Cantidad",
    "Unit": "Unidad",
    "Minutes": "Minutos",
    "Hours": "Horas",
    "Days": "Días",
    "Subject": "Asunto",
    "Tag presence": "Presencia de etiqueta",
    "Contact field": "Campo de contacto",
    "Message content": "Contenido del mensaje",
    "Time of day": "Hora del día",
    "Operand": "Operando",
    "HH:mm-HH:mm": "HH:mm-HH:mm",
    "name / email / company": "nombre / correo / empresa",
    "tag id": "ID de etiqueta",
    "URL": "URL",
    "Headers": "Encabezados",
    '{"Authorization": "Bearer ..."}': '{"Authorization": "Bearer ..."}',
    "Body template": "Plantilla del cuerpo",
    '{"id": "{{ contact.id }}"}': '{"id": "{{ contact.id }}"}',
    "Match type": "Tipo de coincidencia",
    "Exact": "Exacta",
    'Sets the conversation status to "closed". No configuration needed.': 'Establece el estado de la conversación como "cerrada". No se necesita configuración.',

    # ── Flows ──
    "Build branching, button-driven WhatsApp conversations. Useful for menus, FAQs, and triage before a human steps in.": "Construye conversaciones de WhatsApp ramificadas guiadas por botones. Útil para menús, preguntas frecuentes y triaje antes de que un humano intervenga.",
    "New flow": "Nuevo flujo",
    "statusDraft": "Borrador",
    "statusActive": "Activo",
    "statusArchived": "Archivado",
    "Couldn't load flows.": "No se pudieron cargar los flujos.",
    "Couldn't create flow.": "No se pudo crear el flujo.",
    "Clone failed": "Error al clonar",
    'Delete "{name}"? Any active runs will end immediately.': '¿Eliminar "{name}"? Las ejecuciones activas terminarán inmediatamente.',
    "Flow deleted.": "Flujo eliminado.",
    "Couldn't delete flow.": "No se pudo eliminar el flujo.",
    "No flows yet": "Aún sin flujos",
    "Build your first conversation — a welcome menu, an order lookup, an FAQ bot.": "Construye tu primera conversación — un menú de bienvenida, una consulta de pedidos, un bot de preguntas frecuentes.",
    "Create your first flow": "Crea tu primer flujo",
    "Create a new flow": "Crear un nuevo flujo",
    "Start from a template or build from scratch.": "Empieza desde una plantilla o construye desde cero.",
    "Start from a template": "Empezar desde una plantilla",
    "{count} {count, plural, =1 {node} other {nodes}}": "{count} {count, plural, =1 {nodo} other {nodos}}",
    "Or start blank": "O empezar vacío",
    "e.g. Welcome menu": "ej. Menú de bienvenida",
    "Create blank flow": "Crear flujo vacío",
    "{count} {count, plural, =1 {run} other {runs}}": "{count} {count, plural, =1 {ejecución} other {ejecuciones}}",
    "Triggers on keyword (none set)": "Se activa por palabra clave (ninguna configurada)",
    "Triggers on: {keywords}": "Se activa por: {keywords}",
    "Triggers on a contact's first-ever inbound message": "Se activa en el primer mensaje entrante de un contacto",
    "Manual trigger": "Disparo manual",

    # Flow edit
    "Flow not found.": "Flujo no encontrado.",
    "← Back to flows": "← Volver a flujos",
    "Couldn't load flow.": "No se pudo cargar el flujo.",

    # Flow logs
    "Runs": "Ejecuciones",
    "The 50 most recent times this flow ran. Expand a row to see the engine's per-step log.": "Las 50 veces más recientes que este flujo se ejecutó. Expande una fila para ver el registro paso a paso del motor.",
    "No runs yet. Trigger the flow from a personal WhatsApp number to see it appear here.": "Aún sin ejecuciones. Dispara el flujo desde un número de WhatsApp personal para que aparezca aquí.",
    "Couldn't load runs.": "No se pudieron cargar las ejecuciones.",
    "at {node}": "en {node}",
    "Started {time}": "Iniciado {time}",
    "{count} re-prompts": "{count} re-preguntas",
    "ran for {duration}": "duró {duration}",
    "Captured vars ({count})": "Variables capturadas ({count})",
    "No events recorded for this run.": "Sin eventos registrados para esta ejecución.",
    "Completed": "Completada",
    "Handed off": "Transferida",
    "Timed out": "Tiempo agotado",
    "Paused by agent": "Pausada por agente",

    # Flow builder
    "Trigger": "Disparador",
    "When…": "Cuando…",
    "A message contains a keyword": "Un mensaje contiene una palabra clave",
    "Customer's first ever inbound message": "Primer mensaje entrante del cliente",
    "Manual only (no auto-trigger)": "Solo manual (sin disparo automático)",
    "Keywords (comma-separated)": "Palabras clave (separadas por comas)",
    "support, help, hi": "soporte, ayuda, hola",
    "Entry node:": "Nodo de entrada:",
    "Pick the first node…": "Elige el primer nodo…",
    "Nodes ({count})": "Nodos ({count})",
    'Add a <strong>Start</strong> node, then a <strong>Send buttons</strong> node, then a <strong>Handoff</strong> — that\'s the welcome-menu shape from the brief.': 'Añade un nodo <strong>Inicio</strong>, luego un nodo <strong>Enviar botones</strong>, luego una <strong>Transferencia</strong> — esa es la forma del menú de bienvenida.',
    "Add node": "Añadir nodo",
    "Set as entry": "Establecer como entrada",
    "Remove node": "Quitar nodo",
    "Show advanced": "Mostrar avanzado",
    "Hide advanced": "Ocultar avanzado",
    "Node key (internal identifier — keep stable for analytics)": "Clave del nodo (identificador interno — mantenlo estable para análisis)",
    "Reply IDs for each option are shown inline above.": "Los IDs de respuesta para cada opción se muestran en línea arriba.",
    "Entry": "Entrada",
    "No nodes yet.": "Aún sin nodos.",
    "Delete node": "Eliminar nodo",
    "Canvas": "Lienzo",
    "List": "Lista",
    "No node selected": "Ningún nodo seleccionado",
    "Select a node on the canvas to edit its configuration.": "Selecciona un nodo en el lienzo para editar su configuración.",

    # Flow builder form
    "Advances to": "Avanza a",
    "Text sent to the customer": "Texto enviado al cliente",
    "Prompt sent to the customer": "Mensaje enviado al cliente",
    "Variable key (stored in flow_runs.vars; alphanumeric + underscore)": "Clave de variable (almacenada en flow_runs.vars; alfanumérico + guión bajo)",
    "e.g. name, email, company": "ej. nombre, correo, empresa",
    "Interpolate in downstream prompts and handoff notes with": "Interpola en mensajes posteriores y notas de transferencia con",
    "After capturing, advance to": "Después de capturar, avanzar a",
    "Internal note (for the agent picking up)": "Nota interna (para el agente que retoma)",
    "Terminal node. When the runner reaches this node the run is marked complete. No config needed.": "Nodo terminal. Cuando el ejecutor llega a este nodo, la ejecución se marca como completada. No necesita configuración.",
    "Body text": "Texto del cuerpo",
    "Footer (optional, 60 chars)": "Pie de página (opcional, 60 caracteres)",
    "Buttons (1–3) — each one routes to a different next node": "Botones (1–3) — cada uno dirige a un nodo siguiente diferente",
    "Visible title (≤20 chars)": "Título visible (≤20 caracteres)",
    "Next node…": "Siguiente nodo…",
    "Add button": "Añadir botón",
    "Tap-to-expand button label (≤20 chars)": "Etiqueta del botón para expandir (≤20 caracteres)",
    "Rows (1–10 total across all sections)": "Filas (1–10 en total entre todas las secciones)",
    "Section {count} title (optional)": "Título de sección {count} (opcional)",
    "Row title (≤24)": "Título de fila (≤24)",
    "Add row": "Añadir fila",
    "Add section": "Añadir sección",
    "If": "Si",
    "Captured variable": "Variable capturada",
    "Contact has tag": "El contacto tiene etiqueta",
    "Contact field": "Campo de contacto",
    "var name": "nombre de var",
    "Pick a tag…": "Elige una etiqueta…",
    "Pick a field…": "Elige un campo…",
    "is present": "está presente",
    "is absent": "está ausente",
    "equals": "es igual a",
    "contains": "contiene",
    "If true → advance to": "Si verdadero → avanzar a",
    "If false → advance to": "Si falso → avanzar a",
    "Add tag": "Añadir etiqueta",
    "Remove tag": "Quitar etiqueta",
    "Tag UUID": "UUID de etiqueta",
    "Then advance to": "Luego avanzar a",
    "Media type": "Tipo de archivo",
    "Image (PNG, JPEG, WebP)": "Imagen (PNG, JPEG, WebP)",
    "Video (MP4, 3GP)": "Video (MP4, 3GP)",
    "Document (PDF, Word, Excel, PowerPoint, TXT)": "Documento (PDF, Word, Excel, PowerPoint, TXT)",
    "File": "Archivo",
    "Remove file": "Eliminar archivo",
    "Uploading…": "Subiendo…",
    "Click to upload (max 16 MB)": "Haz clic para subir (máx 16 MB)",
    "Caption (optional, shown under the media)": "Pie de foto (opcional, se muestra debajo del archivo)",
    "Filename shown to the customer (documents only)": "Nombre de archivo mostrado al cliente (solo documentos)",
    "invoice.pdf": "factura.pdf",
    "After sending, advance to": "Después de enviar, avanzar a",
    "Pick a next node…": "Elige un siguiente nodo…",
    "— None —": "— Ninguno —",

    # Flow node categories
    "Messaging": "Mensajería",
    "Logic & data": "Lógica y datos",
    "Flow control": "Control de flujo",

    # Flow node types
    "Start": "Inicio",
    "Entry point of the flow": "Punto de entrada del flujo",
    "Send message": "Enviar mensaje",
    "Sends a WhatsApp text message": "Envía un mensaje de texto de WhatsApp",
    "Send buttons": "Enviar botones",
    "Sends quick-reply buttons": "Envía botones de respuesta rápida",
    "Send list": "Enviar lista",
    "Sends a tappable list of options": "Envía una lista de opciones seleccionables",
    "Send media": "Enviar archivo",
    "Sends an image, video, or document": "Envía una imagen, video o documento",
    "Collect input": "Recolectar entrada",
    "Asks a question, saves the reply": "Hace una pregunta, guarda la respuesta",
    "If / else": "Si / sino",
    "Branches on a rule": "Se ramifica según una regla",
    "Tag contact": "Etiquetar contacto",
    "Adds or removes a contact tag": "Añade o quita una etiqueta de contacto",
    "Handoff to agent": "Transferir a agente",
    "Hands the conversation to a human": "Transfiere la conversación a un humano",
    "End": "Fin",
    "Ends the flow": "Termina el flujo",

    # Flow validation
    "No issues. Ready to activate.": "Sin problemas. Listo para activar.",
    "{errorCount} {errorCount, plural, =1 {error} other {errors}}, {warningCount} {warningCount, plural, =1 {warning} other {warnings}}": "{errorCount} {errorCount, plural, =1 {error} other {errores}}, {warningCount} {warningCount, plural, =1 {advertencia} other {advertencias}}",
    "Jump to node {key}": "Ir al nodo {key}",

    # Flow editor state
    "Saved.": "Guardado.",
    "Fix the issues below before activating.": "Corrige los problemas abajo antes de activar.",
    "Flow activated.": "Flujo activado.",
    "Archived.": "Archivado.",
    "Saved as draft.": "Guardado como borrador.",

    # Flow summary
    "{count} {count, plural, =1 {option} other {options}}": "{count} {count, plural, =1 {opción} other {opciones}}",
    "{rowCount} {rowCount, plural, =1 {option} other {options}} across {sectionCount} {sectionCount, plural, =1 {section} other {sections}}": "{rowCount} {rowCount, plural, =1 {opción} other {opciones}} en {sectionCount} {sectionCount, plural, =1 {sección} other {secciones}}",
    "{label} (no file uploaded)": "{label} (sin archivo subido)",
    "Media": "Archivo",
    "Image": "Imagen",
    "has tag {tag}": "tiene etiqueta {tag}",
    "exists": "existe",
    "missing": "falta",
    "{mode} tag {tag}…": "{mode} etiqueta {tag}…",
    "{mode} tag (none picked)": "{mode} etiqueta (ninguna seleccionada)",

    # ── Settings ──
    "Everything in one place — your account and your workspace. Pick a section to manage it.": "Todo en un solo lugar — tu cuenta y tu espacio de trabajo. Elige una sección para gestionarla.",
    "Not set up yet": "Aún no configurado",
    "Connected": "Conectado",
    "Needs reconnecting": "Necesita reconexión",
    "View team members": "Ver miembros del equipo",
    "{count} {count, plural, =1 {member} other {members}}": "{count} {count, plural, =1 {miembro} other {miembros}}",
    "{count} pending {count, plural, =1 {invite} other {invites}}": "{count} {count, plural, =1 {invitación pendiente} other {invitaciones pendientes}}",
    "Manage message templates": "Gestionar plantillas de mensajes",
    "{count} {count, plural, =1 {template} other {templates}}": "{count} {count, plural, =1 {plantilla} other {plantillas}}",
    "{count} pending review": "{count} pendiente de revisión",
    "Tags and custom fields": "Etiquetas y campos personalizados",
    "{count} {count, plural, =1 {tag} other {tags}}": "{count} {count, plural, =1 {etiqueta} other {etiquetas}}",
    "{count} custom {count, plural, =1 {field} other {fields}}": "{count} campo {count, plural, =1 {personalizado} other {personalizados}}",
    "{mode} mode · {theme} accent": "Modo {mode} · Acento {theme}",
    "Your account": "Tu cuenta",
    "Loading…": "Cargando…",

    # Team members
    "Team members": "Miembros del equipo",
    "People with access to this account. Roles control what each teammate can do.": "Personas con acceso a esta cuenta. Los roles controlan lo que cada miembro puede hacer.",
    "Invite member": "Invitar miembro",
    "online": "en línea",
    "away": "ausente",
    "offline": "desconectado",
    "You": "Tú",
    "Joined {date}": "Se unió {date}",
    "Remove": "Eliminar",
    "Removed {name}": "{name} eliminado",
    "Updated {name} to {role}": "{name} actualizado a {role}",
    "Pending invitations": "Invitaciones pendientes",
    "The plaintext invite URL is only shown once at creation for security — to re-share, revoke the invite below and create a new one.": "La URL de invitación en texto plano solo se muestra una vez al crearla por seguridad — para reenviarla, revoca la invitación abajo y crea una nueva.",
    "No pending invitations.": "Sin invitaciones pendientes.",
    "Click <bold>Invite member</bold> above to generate a shareable link.": "Haz clic en <bold>Invitar miembro</bold> arriba para generar un enlace compartible.",
    "Untitled invite": "Invitación sin título",
    "expires in {days} {days, plural, =1 {day} other {days}}": "expira en {days} {days, plural, =1 {día} other {días}}",
    "expires in {hours} {hours, plural, =1 {hour} other {hours}}": "expira en {hours} {hours, plural, =1 {hora} other {horas}}",
    "expired": "expirada",
    "Revoke": "Revocar",
    "Invitation revoked": "Invitación revocada",
    "Remove member": "Eliminar miembro",
    "Remove <bold>{name}</bold> from the account? They'll be signed out of this account and given a fresh personal account on their next sign-in. Their login isn't deleted.": "¿Eliminar a <bold>{name}</bold> de la cuenta? Se cerrará su sesión de esta cuenta y recibirán una cuenta personal nueva en su próximo inicio de sesión. Su inicio de sesión no se elimina.",
    "Removing...": "Eliminando...",
    "Remove member": "Eliminar miembro",

    # Invite dialog
    "Invite created": "Invitación creada",
    "Share this link with your new teammate.": "Comparte este enlace con tu nuevo compañero.",
    "Invite link": "Enlace de invitación",
    "Save this link now.": "Guarda este enlace ahora.",
    "We never store the plaintext — once you close this dialog the URL is gone.": "Nunca almacenamos el texto plano — una vez que cierres este diálogo, la URL desaparece.",
    "Send via WhatsApp": "Enviar por WhatsApp",
    "Done": "Listo",
    "Invite a teammate": "Invitar a un compañero",
    "Generate a one-time invite link. Share it via WhatsApp, Slack, or any channel you like — no email service required.": "Genera un enlace de invitación de un solo uso. Compártelo por WhatsApp, Slack o cualquier canal que prefieras — no se requiere servicio de correo.",
    "Role": "Rol",
    "Link valid for": "Enlace válido por",
    "1 day": "1 día",
    "7 days": "7 días",
    "30 days": "30 días",
    "Label": "Etiqueta",
    "(optional)": "(opcional)",
    "e.g. Sara — support team": "ej. Sara — equipo de soporte",
    "Helps you remember who you sent the link to in the pending list below.": "Te ayuda a recordar a quién enviaste el enlace en la lista de pendientes abajo.",
    "Generate link": "Generar enlace",
    "Label must be {max} characters or fewer": "La etiqueta debe tener {max} caracteres o menos",
    "Invite link copied": "Enlace de invitación copiado",
    "Clipboard blocked — copy the link manually": "Portapapeles bloqueado — copia el enlace manualmente",
    "Join {accountName} on wacrm using this link (valid for {expiresInDays} days): {url}": "Únete a {accountName} en wacrm usando este enlace (válido por {expiresInDays} días): {url}",

    # Fields & tags
    "Fields & tags": "Campos y etiquetas",
    "Two ways to organize contacts: colour-coded tags for quick grouping, and custom fields for structured data.": "Dos formas de organizar contactos: etiquetas de colores para agrupación rápida y campos personalizados para datos estructurados.",
    "Tags": "Etiquetas",
    "Colour-coded labels for grouping and filtering contacts.": "Etiquetas de colores para agrupar y filtrar contactos.",
    "Extra contact fields (e.g. ZIP code, lead source). They appear on every contact and in the \"Update Contact Field\" automation action.": "Campos de contacto adicionales (ej. código postal, fuente del lead). Aparecen en cada contacto y en la acción de automatización \"Actualizar campo de contacto\".",
    "Admin": "Admin",
    "Failed to load tags": "Error al cargar etiquetas",
    "Tag name is required": "El nombre de la etiqueta es obligatorio",
    "Not authenticated": "No autenticado",
    "Tag created": "Etiqueta creada",
    "Failed to create tag": "Error al crear etiqueta",
    "Tag deleted": "Etiqueta eliminada",
    "Failed to delete tag": "Error al eliminar etiqueta",
    "Delete {name}": "Eliminar {name}",
    "No tags yet — create your first one below.": "Aún sin etiquetas — crea la primera abajo.",
    "e.g. Newsletter": "ej. Boletín",
    "Use {color}": "Usar {color}",
    "Add tag": "Añadir etiqueta",
    "Delete tag": "Eliminar etiqueta",
    'Delete the tag "{name}"? This removes it from all contacts and cannot be undone.': '¿Eliminar la etiqueta "{name}"? Esto la quita de todos los contactos y no se puede deshacer.',
    "Red": "Rojo",
    "Orange": "Naranja",
    "Amber": "Ámbar",
    "Emerald": "Esmeralda",
    "Cyan": "Cian",
    "Blue": "Azul",
    "Violet": "Violeta",
    "Pink": "Rosa",

    # Message templates
    "Message templates": "Plantillas de mensajes",
    'Create templates and submit them to Meta for approval. Use "Sync from Meta" to pull templates approved elsewhere.': 'Crea plantillas y envíalas a Meta para aprobación. Usa "Sincronizar desde Meta" para traer plantillas aprobadas externamente.',
    "Sync from Meta": "Sincronizar desde Meta",
    "Syncing…": "Sincronizando…",
    "Pull approved templates from your Meta WhatsApp Business Account": "Trae plantillas aprobadas desde tu cuenta de Meta WhatsApp Business",
    "New Template": "Nueva plantilla",
    "No templates yet.": "Aún sin plantillas.",
    "Create your first message template to get started.": "Crea tu primera plantilla de mensaje para empezar.",
    "Editing triggers Meta re-review — status flips to PENDING.": "Editar provoca una revisión de Meta — el estado cambia a PENDIENTE.",
    "Edit template": "Editar plantilla",
    "Edit the template and resubmit to Meta for review.": "Edita la plantilla y vuelve a enviarla a Meta para revisión.",
    "Edit and resubmit template": "Editar y reenviar plantilla",
    "Resubmit": "Reenviar",
    "Delete template from Meta and locally": "Eliminar plantilla de Meta y localmente",
    "Delete template locally": "Eliminar plantilla localmente",
    "Delete from Meta and locally": "Eliminar de Meta y localmente",
    "Delete locally": "Eliminar localmente",
    "Edit Message Template": "Editar plantilla de mensaje",
    "New Message Template": "Nueva plantilla de mensaje",
    "Save your changes to re-submit to Meta. Status will flip back to PENDING during review.": "Guarda tus cambios para reenviar a Meta. El estado volverá a PENDIENTE durante la revisión.",
    "Build a template and submit it to Meta for approval.": "Construye una plantilla y envíala a Meta para aprobación.",
    "AUTHENTICATION templates have a fixed body + OTP button shape that needs a different builder.": "Las plantillas AUTENTICACIÓN tienen un formato fijo de cuerpo + botón OTP que necesita un constructor diferente.",
    "Template Name": "Nombre de la plantilla",
    "e.g. order_confirmation": "ej. confirmacion_pedido",
    "Name is fixed once a template exists on Meta — create a new template to change it.": "El nombre se fija una vez que la plantilla existe en Meta — crea una nueva plantilla para cambiarlo.",
    "Lowercase letters, digits, and underscores only.": "Solo minúsculas, dígitos y guiones bajos.",
    "Category": "Categoría",
    "Language": "Idioma",
    "Language is fixed once a template exists on Meta.": "El idioma se fija una vez que la plantilla existe en Meta.",
    "Must match the exact code on Meta — <code>en_US</code> and <code>en</code> are distinct.": "Debe coincidir con el código exacto en Meta — <code>en_US</code> y <code>en</code> son distintos.",
    "Header": "Encabezado",
    "None": "Ninguno",
    "Text": "Texto",
    "Image": "Imagen",
    "Header text (max 60 chars, optional {{1}})": "Texto del encabezado (máx 60 caracteres, {{1}} opcional)",
    "Sample value for header variable": "Valor de muestra para la variable del encabezado",
    "Sample value for {{1}} (required for Meta review)": "Valor de muestra para {{1}} (requerido para revisión de Meta)",
    "Upload image": "Subir imagen",
    "JPEG or PNG, ≤5 MB": "JPEG o PNG, ≤5 MB",
    "https://… (or paste a public {format} link)": "https://… (o pega un enlace público {format})",
    "Upload a JPEG/PNG (≤5 MB, ≥800×418 px recommended) or paste a public HTTPS link — we upload it to Meta for review automatically.": "Sube un JPEG/PNG (≤5 MB, ≥800×418 px recomendado) o pega un enlace HTTPS público — lo subimos a Meta para revisión automáticamente.",
    "Must be a publicly accessible HTTPS link. Meta fetches it once during review, so it needs to stay live for ~24 hrs.": "Debe ser un enlace HTTPS de acceso público. Meta lo obtiene una vez durante la revisión, así que debe estar activo ~24 h.",
    " Recommended: MP4 / 3GPP, ≤16 MB, ≤60 seconds.": " Recomendado: MP4 / 3GPP, ≤16 MB, ≤60 segundos.",
    " Recommended: PDF, ≤100 MB.": " Recomendado: PDF, ≤100 MB.",
    "Body Text": "Texto del cuerpo",
    "Hello {{1}}, your order {{2}} is confirmed.": "Hola {{1}}, tu pedido {{2}} está confirmado.",
    "Use {{1}}, {{2}} for variables (must be contiguous starting at {{1}}).": "Usa {{1}}, {{2}} para variables (deben ser consecutivas empezando por {{1}}).",
    "Sample values (Meta uses these to review your template)": "Valores de muestra (Meta los usa para revisar tu plantilla)",
    "Sample value for body variable {var}": "Valor de muestra para variable de cuerpo {var}",
    "Sample for {var}": "Muestra para {var}",
    "Footer (optional)": "Pie de página (opcional)",
    "Optional footer text (max 60 chars)": "Texto opcional de pie de página (máx 60 caracteres)",
    "Buttons (optional)": "Botones (opcional)",
    "Add Button": "Añadir botón",
    "Up to {max} buttons. QUICK_REPLY buttons must come before URL / phone / copy-code buttons.": "Hasta {max} botones. Los botones QUICK_REPLY deben ir antes que los de URL / teléfono / copiar código.",
    "Quick Reply": "Respuesta rápida",
    "URL": "URL",
    "Phone": "Teléfono",
    "Copy Code": "Copiar código",
    "Button label": "Etiqueta del botón",
    "https://example.com/path or with {{1}} suffix": "https://ejemplo.com/ruta o con sufijo {{1}}",
    "Example value for {{1}} (required when URL has a variable)": "Valor de ejemplo para {{1}} (requerido cuando la URL tiene variable)",
    "Example code (e.g. SUMMER20)": "Código de ejemplo (ej. VERANO20)",
    "Submitting…": "Enviando…",
    "Save & Resubmit": "Guardar y reenviar",
    "Submit for Approval": "Enviar para aprobación",
    "Delete template?": "¿Eliminar plantilla?",
    '"{name}" will be deleted from Meta and from wacrm.': '"{name}" se eliminará de Meta y de wacrm.',
    '"{name}" will be deleted from wacrm.': '"{name}" se eliminará de wacrm.',
    "Delete": "Eliminar",
    "Failed to load templates": "Error al cargar plantillas",
    "Failed to submit": "Error al enviar",
    "Edit submitted — Meta typically reviews within 24 hours.": "Edición enviada — Meta suele revisar en 24 horas.",
    "Submitted to Meta — typical review time is 24 hours.": "Enviado a Meta — el tiempo típico de revisión es 24 horas.",
    "Template updated (dry-run — no Meta call)": "Plantilla actualizada (simulación — sin llamada a Meta)",
    "Template saved (dry-run — no Meta call)": "Plantilla guardada (simulación — sin llamada a Meta)",
    "Synced {total} {total, plural, =1 {template} other {templates}} from Meta": "Sincronizadas {total} {total, plural, =1 {plantilla} other {plantillas}} de Meta",
    " ({inserted} new, {updated} updated)": " ({inserted} nuevas, {updated} actualizadas)",
    "Failed to sync: {preview}": "Error al sincronizar: {preview}",
    "Synced the first 2000 templates only — your account has more.": "Sincronizadas solo las primeras 2000 plantillas — tu cuenta tiene más.",
    "Failed to sync templates": "Error al sincronizar plantillas",
    "Template deleted": "Plantilla eliminada",
    "Failed to delete template": "Error al eliminar plantilla",
    "Header image must be a JPEG or PNG.": "La imagen de encabezado debe ser JPEG o PNG.",
    "Image is {size} MB — Meta's limit is 5 MB.": "La imagen es de {size} MB — el límite de Meta es 5 MB.",
    "Image uploaded.": "Imagen subida.",
    "Upload failed.": "Error al subir.",

    # Roles
    "adminHint": "Gestionar miembros + todo",
    "agentHint": "Usar funciones; sin configuración",
    "viewerHint": "Solo lectura en toda la app",
    "ownerHint": "Control total de la cuenta y facturación",

    # WhatsApp connection
    "WhatsApp connection": "Conexión de WhatsApp",
    "Connect your Meta WhatsApp Business API. Credentials, webhook, and setup steps all live here.": "Conecta tu API de Meta WhatsApp Business. Credenciales, webhook y pasos de configuración viven aquí.",
    "Stored token can't be decrypted": "El token almacenado no se puede descifrar",
    "Resetting...": "Reiniciando...",
    "Reset Configuration": "Restablecer configuración",
    "Credentials valid": "Credenciales válidas",
    "Not Connected": "No conectado",
    "Your access token authenticates with Meta.": "Tu token de acceso autentica con Meta.",
    "Configure your Meta API credentials below to connect your WhatsApp Business account.": "Configura tus credenciales de Meta API abajo para conectar tu cuenta de WhatsApp Business.",
    "Registered — Meta will deliver events to wacrm": "Registrado — Meta entregará eventos a wacrm",
    "Not registered — Meta will not deliver events": "No registrado — Meta no entregará eventos",
    "Verify with Meta": "Verificar con Meta",
    "Subscribed since {date}. Click Verify with Meta if events stop arriving.": "Suscrito desde {date}. Haz clic en Verificar con Meta si los eventos dejan de llegar.",
    "unknown": "desconocido",
    "Last attempt failed with: ": "El último intento falló con: ",
    "Enter (or correct) the 2-step PIN below and click Save Configuration to retry.": "Ingresa (o corrige) el PIN de 2 pasos abajo y haz clic en Guardar configuración para reintentar.",
    "This number was saved before registration tracking existed.": "Este número se guardó antes de que existiera el registro.",
    "Diagnostic — last run: ": "Diagnóstico — última ejecución: ",
    "live": "activo",
    "not live": "no activo",
    "API Credentials": "Credenciales API",
    "Enter your Meta WhatsApp Business API credentials.": "Ingresa tus credenciales de Meta WhatsApp Business API.",
    "Phone Number ID": "ID de número de teléfono",
    "WhatsApp Business Account ID": "ID de cuenta de WhatsApp Business",
    "Permanent Access Token": "Token de acceso permanente",
    "Enter your access token": "Ingresa tu token de acceso",
    "Token is hidden for security. Re-enter it to update configuration.": "El token está oculto por seguridad. Vuelve a ingresarlo para actualizar la configuración.",
    "Webhook Verify Token": "Token de verificación del webhook",
    "Create a custom verify token": "Crea un token de verificación personalizado",
    "A custom string you create. Must match the token you set in Meta webhook settings.": "Una cadena personalizada que creas. Debe coincidir con el token que configuraste en los ajustes del webhook de Meta.",
    "Two-step verification PIN": "PIN de verificación en dos pasos",
    "6-digit PIN from Meta WhatsApp Manager": "PIN de 6 dígitos de Meta WhatsApp Manager",
    "Webhook Configuration": "Configuración del webhook",
    "Use this URL as your webhook callback in the Meta App Dashboard.": "Usa esta URL como callback del webhook en el panel de Meta App.",
    "Webhook Callback URL": "URL de callback del webhook",
    "Save Configuration": "Guardar configuración",
    "Testing...": "Probando...",
    "Test API Connection": "Probar conexión API",
    "Setup Instructions": "Instrucciones de configuración",
    "Follow these steps to connect your WhatsApp Business API.": "Sigue estos pasos para conectar tu API de WhatsApp Business.",
    "Create a Meta App": "Crear una aplicación Meta",
    "Go to developers.facebook.com": "Ve a developers.facebook.com",
    'Click "My Apps" and then "Create App"': 'Haz clic en "Mis aplicaciones" y luego "Crear aplicación"',
    'Select "Business" as the app type': 'Selecciona "Negocio" como tipo de aplicación',
    "Fill in app details and create": "Completa los detalles de la aplicación y crea",
    "Add WhatsApp Product": "Añadir producto WhatsApp",
    'In your app dashboard, click "Add Product"': 'En el panel de tu aplicación, haz clic en "Añadir producto"',
    'Find "WhatsApp" and click "Set Up"': 'Encuentra "WhatsApp" y haz clic en "Configurar"',
    "Follow the setup wizard to link your business": "Sigue el asistente de configuración para vincular tu negocio",
    "Get API Credentials": "Obtener credenciales API",
    "Go to WhatsApp > API Setup": "Ve a WhatsApp > Configuración API",
    'Copy your <strong class="text-foreground">Phone Number ID</strong>': 'Copia tu <strong class="text-foreground">ID de número de teléfono</strong>',
    'Copy your <strong class="text-foreground">WhatsApp Business Account ID</strong>': 'Copia tu <strong class="text-foreground">ID de cuenta de WhatsApp Business</strong>',
    'Generate a <strong class="text-foreground">Permanent Access Token</strong> from Business Settings > System Users': 'Genera un <strong class="text-foreground">Token de acceso permanente</strong> desde Configuración de negocio > Usuarios del sistema',
    "Configure Webhooks": "Configurar webhooks",
    "Go to WhatsApp > Configuration": "Ve a WhatsApp > Configuración",
    'Click "Edit" on the Webhook section': 'Haz clic en "Editar" en la sección de Webhook',
    'Paste the <strong class="text-foreground">Webhook Callback URL</strong> from above': 'Pega la <strong class="text-foreground">URL de callback del webhook</strong> de arriba',
    'Enter the same <strong class="text-foreground">Verify Token</strong> you set here': 'Ingresa el mismo <strong class="text-foreground">Token de verificación</strong> que configuraste aquí',
    'Subscribe to "messages" webhook field': 'Suscríbete al campo de webhook "messages"',
    "Meta WhatsApp API Documentation": "Documentación de Meta WhatsApp API",

    # Settings sections
    "Overview": "Resumen",
    "Your profile": "Tu perfil",
    "Login & security": "Inicio de sesión y seguridad",
    "Appearance": "Apariencia",
    "WhatsApp": "WhatsApp",
    "Deals & currency": "Negocios y moneda",
    "API keys": "Claves API",
    "Account": "Cuenta",
    "Workspace": "Espacio de trabajo",

    # Profile
    "How you show up across the app. Your avatar and name appear in the header, sidebar, and anywhere your teammates see you.": "Cómo te muestras en la aplicación. Tu avatar y nombre aparecen en el encabezado, la barra lateral y dondequiera que te vean tus compañeros.",
    "Change photo": "Cambiar foto",
    "Upload photo": "Subir foto",
    "Remove": "Eliminar",
    "PNG, JPG, WebP, or GIF. Up to 2 MB.": "PNG, JPG, WebP o GIF. Hasta 2 MB.",
    "Display name": "Nombre mostrado",
    "Check the inbox for <bold>{oldEmail}</bold> and <bold>{newEmail}</bold> — both need to confirm before the change takes effect.": "Revisa la bandeja de <bold>{oldEmail}</bold> y <bold>{newEmail}</bold> — ambos deben confirmar antes de que el cambio surta efecto.",
    "Account details": "Detalles de la cuenta",
    "Joined": "Se unió",
    "User ID": "ID de usuario",
    "Loading your profile…": "Cargando tu perfil…",
    "Saving…": "Guardando…",
    "Save changes": "Guardar cambios",
    "Unsupported image type": "Tipo de imagen no soportado",
    "Use PNG, JPG, WebP, or GIF.": "Usa PNG, JPG, WebP o GIF.",
    "Image is too large": "La imagen es demasiado grande",
    "Maximum 2 MB.": "Máximo 2 MB.",
    "Display name is required": "El nombre mostrado es obligatorio",
    "Enter a valid email address": "Ingresa una dirección de correo válida",
    "Upload failed: {message}": "Error al subir: {message}",
    "Save failed: {message}": "Error al guardar: {message}",
    "Profile saved": "Perfil guardado",
    "Email change failed: {message}": "Error al cambiar correo: {message}",
    "Profile saved — check your email to confirm the address change": "Perfil guardado — revisa tu correo para confirmar el cambio de dirección",
    "Use at least {min} characters. You will stay signed in on this device after changing it.": "Usa al menos {min} caracteres. Permanecerás conectado en este dispositivo después de cambiarla.",
    "Current password": "Contraseña actual",
    "New password": "Nueva contraseña",
    "Confirm new password": "Confirmar nueva contraseña",
    "Updating…": "Actualizando…",
    "Update password": "Actualizar contraseña",
    "Cannot change password without a current email": "No se puede cambiar la contraseña sin un correo actual",
    "Password must be at least {min} characters": "La contraseña debe tener al menos {min} caracteres",
    "New password and confirmation do not match": "La nueva contraseña y la confirmación no coinciden",
    "Current password is incorrect": "La contraseña actual es incorrecta",
    "Password update failed: {message}": "Error al actualizar contraseña: {message}",
    "Password updated": "Contraseña actualizada",
    "Active sessions": "Sesiones activas",
    'Sign out of every device where you\'re logged in — including this one.': 'Cierra sesión en todos los dispositivos donde hayas iniciado sesión — incluido este.',
    "Sign out of all devices": "Cerrar sesión en todos los dispositivos",
    "Sign out everywhere?": "¿Cerrar sesión en todas partes?",
    "Every device logged into this account will be signed out and will need to log in again.": "Todos los dispositivos con sesión iniciada en esta cuenta se desconectarán y deberán iniciar sesión nuevamente.",
    "Signing out…": "Cerrando sesión…",
    "Sign out everywhere": "Cerrar sesión en todas partes",
    "Sign-out failed: {message}": "Error al cerrar sesión: {message}",

    # Appearance
    "Set the mode and accent colour used across the app. Saved to this device — try it, it changes live.": "Establece el modo y el color de acento usados en la aplicación. Se guarda en este dispositivo — pruébalo, cambia en vivo.",
    "Mode": "Modo",
    "Use {mode} mode": "Usar modo {mode}",
    "Accent color": "Color de acento",
    "Use {name} theme": "Usar tema {name}",

    # Login & security
    "Change your password and sign out of your devices. These keep your account safe.": "Cambia tu contraseña y cierra sesión en tus dispositivos. Estas acciones mantienen segura tu cuenta.",

    # API keys
    "Keys authenticate the public REST API (<apiCode>/api/v1</apiCode>) so you can build your own automations.": "Las claves autentican la API REST pública (<apiCode>/api/v1</apiCode>) para que puedas construir tus propias automatizaciones.",
    "New API key": "Nueva clave API",
    "No API keys yet.": "Aún sin claves API.",
    "Click <bold>New API key</bold> to create one.": "Haz clic en <bold>Nueva clave API</bold> para crear una.",
    "Ask an admin to create one.": "Pide a un administrador que cree una.",
    "Revoked": "Revocada",
    "No scopes": "Sin alcances",
    "last used {date}": "usada por última vez {date}",
    "never used": "nunca usada",
    "expires {date}": "expira {date}",
    'Revoked "{name}"': '"{name}" revocada',
    "Failed to revoke key": "Error al revocar clave",
    "Failed to load API keys": "Error al cargar claves API",
    "Failed to create key": "Error al crear clave",
    "Give the key a name": "Asigna un nombre a la clave",
    "e.g. Zapier automation": "ej. automatización de Zapier",
    "Scopes": "Alcances",
    "Creating…": "Creando…",
    "Create key": "Crear clave",
    "Copy your API key": "Copia tu clave API",
    "This is the only time the full key is shown.": "Esta es la única vez que se muestra la clave completa.",
    "API key": "Clave API",
    "API key copied": "Clave API copiada",
    "Copy failed — select and copy manually": "Error al copiar — selecciona y copia manualmente",
    "New API key": "Nueva clave API",
    "Name it after the integration that will use it, and grant only the scopes it needs.": "Nómbrala según la integración que la usará y concédele solo los alcances que necesita.",
    "Could not reach the server": "No se pudo conectar con el servidor",

    # Deals & currency
    "The currency used for new deals and for pipeline and dashboard totals.": "La moneda usada para nuevos negocios y para totales de tuberías y panel.",
    "Default currency": "Moneda predeterminada",
    "New deals default to this currency, and pipeline and dashboard totals are shown in it.": "Los nuevos negocios usan esta moneda por defecto, y los totales de tubería y panel se muestran en ella.",
    "Currency": "Moneda",
    "Only account admins can change the default currency.": "Solo los administradores de cuenta pueden cambiar la moneda predeterminada.",
    "Failed to save default currency": "Error al guardar moneda predeterminada",
    "Default currency updated": "Moneda predeterminada actualizada",

    # AI config
    "Agent setup": "Configuración del agente",
    "Bring your own OpenAI or Anthropic key.": "Usa tu propia clave de OpenAI o Anthropic.",
    "Only admins and owners can change the AI configuration.": "Solo administradores y propietarios pueden cambiar la configuración de IA.",
    "Failed to load AI configuration": "Error al cargar configuración de IA",
    "Provider & key": "Proveedor y clave",
    "Your key is encrypted at rest (AES-256-GCM) and never shown again after saving.": "Tu clave está cifrada en reposo (AES-256-GCM) y nunca se muestra de nuevo después de guardar.",
    "Provider": "Proveedor",
    "Model": "Modelo",
    "API key": "Clave API",
    "Test key": "Probar clave",
    "Key works — the provider responded.": "La clave funciona — el proveedor respondió.",
    "The provider rejected the request.": "El proveedor rechazó la solicitud.",
    "Could not reach the provider.": "No se pudo conectar con el proveedor.",
    "Embeddings key": "Clave de embeddings",
    "(optional — enables semantic knowledge-base search)": "(opcional — activa la búsqueda semántica en la base de conocimiento)",
    "An OpenAI key used only to embed your knowledge base (text-embedding-3-small){sameKeyText}.": "Una clave de OpenAI usada solo para incorporar tu base de conocimiento (text-embedding-3-small){sameKeyText}.",
    " — can be the same key as above": " — puede ser la misma clave que la de arriba",
    "Behaviour": "Comportamiento",
    "Tell the assistant about your business — products, tone, what it may and may not promise.": "Cuéntale al asistente sobre tu negocio — productos, tono, qué puede y no puede prometer.",
    "Business context & instructions": "Contexto e instrucciones del negocio",
    "e.g. We are Acme, a coffee-equipment store. Be warm and concise. Never quote prices or delivery dates — hand off to a human for those.": "ej. Somos Cafetería Acme, una tienda de equipos de café. Sé amable y conciso. Nunca des precios ni fechas de entrega — transfiere a un humano para eso.",
    "Enable AI assistant": "Activar asistente de IA",
    "Master switch. Turns on the \"Draft with AI\" button in the inbox.": "Interruptor principal. Activa el botón \"Redactar con IA\" en la bandeja de entrada.",
    "Auto-reply to inbound messages": "Responder automáticamente a mensajes entrantes",
    "The bot answers new inbound messages automatically (only when no flow handles them and no agent is assigned).": "El bot responde automáticamente a nuevos mensajes entrantes (solo cuando ningún flujo los maneja y ningún agente está asignado).",
    "Max auto-replies per conversation": "Máx. respuestas automáticas por conversación",
    "After this many bot replies in one thread, the bot goes quiet.": "Después de esta cantidad de respuestas del bot en un hilo, el bot se silencia.",
    "Hand off to": "Transferir a",
    "When the bot can't help — or hits the reply cap — it pauses and routes the chat here.": "Cuando el bot no puede ayudar — o alcanza el límite de respuestas — se pausa y redirige el chat aquí.",
    "Unassigned queue (any agent can pick it up)": "Cola sin asignar (cualquier agente puede tomarla)",
    "Enter a model name.": "Ingresa un nombre de modelo.",
    "Enter your API key.": "Ingresa tu clave API.",
    "AI assistant saved.": "Asistente de IA guardado.",
    "Failed to save.": "Error al guardar.",
    "AI configuration removed.": "Configuración de IA eliminada.",
    "Failed to remove.": "Error al eliminar.",

    # AI Knowledge base
    "Failed to load knowledge base": "Error al cargar base de conocimiento",
    "Failed to open document": "Error al abrir documento",
    "Title and content are required.": "El título y el contenido son obligatorios.",
    "Document added.": "Documento añadido.",
    "Document updated.": "Documento actualizado.",
    "Document removed.": "Documento eliminado.",
    "Reindexed {count} document(s).": "{count} documento(s) reindexado(s).",
    "Reindex failed.": "Error al reindexar.",
    "Knowledge base": "Base de conocimiento",
    "Add FAQs, policies, or product details.": "Añade preguntas frecuentes, políticas o detalles de productos.",
    " Semantic search is on (embeddings key set).": " Búsqueda semántica activada (clave de embeddings configurada).",
    " Using keyword search — add an embeddings key above for semantic search.": " Usando búsqueda por palabras clave — añade una clave de embeddings arriba para búsqueda semántica.",
    "No documents yet.": "Aún sin documentos.",
    "Title": "Título",
    "e.g. Returns & refunds policy": "ej. Política de devoluciones",
    "Content": "Contenido",
    "Paste the FAQ answer, policy text, or product details…": "Pega la respuesta de FAQ, texto de política o detalles del producto…",
    "Save document": "Guardar documento",
    "Add document": "Añadir documento",
    "Reindex": "Reindexar",
    "Re-embed all documents (e.g. after adding an embeddings key)": "Reincorporar todos los documentos (ej. después de añadir una clave de embeddings)",

    # ── Shared / common ──
    "Loading...": "Cargando...",
    "Error": "Error",
    "Success": "Éxito",
    "Save": "Guardar",
    "Saved": "Guardado",
    "Confirm": "Confirmar",
    "Search": "Buscar",
    "Filter": "Filtrar",
    "Sort": "Ordenar",
    "Export": "Exportar",
    "Download": "Descargar",
    "Yes": "Sí",
    "No": "No",
    "On": "Activado",
    "Off": "Desactivado",
    "Enabled": "Activado",
    "Disabled": "Desactivado",
    "Optional": "Opcional",
    "Required": "Obligatorio",
    "more": "más",
    "No data": "Sin datos",
    "Filter by": "Filtrar por",
    "Clear filters": "Limpiar filtros",
    "Something went wrong": "Algo salió mal",
    "Try again": "Intentar de nuevo",
    "Page not found": "Página no encontrada",
    "Go home": "Ir al inicio",
    "Unauthorized": "No autorizado",
    "Forbidden": "Prohibido",
    "Not found": "No encontrado",
    "Server error": "Error del servidor",
    "Network error": "Error de red",
    "Retry": "Reintentar",
    "Sign out": "Cerrar sesión",
    "Sign in": "Iniciar sesión",
    "Jane Doe": "Juan Pérez",
}


def translate_value(value):
    """Translate a string, preserving ICU plurals and variables."""
    if not isinstance(value, str):
        return value
    if value in es:
        return es[value]

    # Try to parse ICU plural expressions and translate non-variable text
    # Split on {variable} patterns
    parts = re.split(r'(\{[^}]+\})', value)
    result = []
    for part in parts:
        if part.startswith('{') and part.endswith('}'):
            result.append(part)
        elif part in es:
            result.append(es[part])
        else:
            result.append(part)

    translated = ''.join(result)
    if translated != value:
        return translated

    return value


def translate_obj(obj, path=""):
    """Recursively translate all strings."""
    if isinstance(obj, dict):
        return {k: translate_obj(v, f"{path}.{k}") for k, v in obj.items()}
    elif isinstance(obj, list):
        return [translate_obj(item, f"{path}[{i}]") for i, item in enumerate(obj)]
    elif isinstance(obj, str):
        return translate_value(obj)
    else:
        return obj


# ── Main ──
src_path = Path("/home/diegol/Documentos/wacrm/messages/en.json")
dst_path = Path("/home/diegol/Documentos/wacrm/messages/es.json")

source = json.loads(src_path.read_text(encoding="utf-8"))

print("🔄 Translating all strings to Spanish...")
translated = translate_obj(source)

# Write output
dst_path.write_text(
    json.dumps(translated, indent=2, ensure_ascii=False) + "\n",
    encoding="utf-8",
)

# Verify
tgt = json.loads(dst_path.read_text(encoding="utf-8"))

# Count all string values translated
def count_strings(obj):
    if isinstance(obj, str):
        return 1
    elif isinstance(obj, dict):
        return sum(count_strings(v) for v in obj.values())
    elif isinstance(obj, list):
        return sum(count_strings(v) for v in obj)
    return 0

def count_untranslated(obj):
    if isinstance(obj, str):
        # Check if it was translated (is Spanish now vs original English)
        return 0  # We just trust our dict
    elif isinstance(obj, dict):
        return sum(count_untranslated(v) for v in obj.values())
    elif isinstance(obj, list):
        return sum(count_untranslated(v) for v in obj)
    return 0

total_strings = count_strings(source)
target_size = len(dst_path.read_text(encoding="utf-8"))
print(f"\n✅ Translation complete!")
print(f"   Total strings translated: {total_strings}")
print(f"   Source: {len(src_path.read_text(encoding='utf-8')):,} bytes")
print(f"   Target: {target_size:,} bytes")
print(f"   Top-level sections: {list(tgt.keys())}")
print(f"   File: {dst_path}")
print(f"\n📋 All strings are in Spanish.")
